
#Virgin
man2025 <- man(qname = "virgin",
               year = 2025,
               dname = "virgin",
               questionText = "Was this your first time visiting Black Rock City?",
               questionType = "selectOne",
               responses = c("Yes, it was my first time",
                             "No, I have been to Black Rock City before",
                             "I did not go to Black Rock City in 2025"),
               rname = c("virgin",
                         "notVirgin",
                         "didNotGoIn2025"),
               reportingValues = c(1, 2, 3)) +

  # Presently at BRC
  man(qname = "atBRC",
      year = 2025,
      dname = "atBRC",
      questionText = "Are you presently at Black Rock City?",
      questionType = "selectOne",
      responses = c("No, I left",
                    "Yes, I am still there",
                    "Yes, but the event is over"),
      rname = c("no",
                "yesStillThere",
                "yesEventOver"),
      reportingValues = c(1, 2, 3)) +

  # Age
  man(qname = "age",
      year = 2025,
      dname = "age",
      questionText = "What was your age when you ARRIVED at Black Rock City this year?",
      questionType = "selectOne",
      responses = as.character(1:100),
      rname = paste0("age", 1:100),
      reportingValues = 1:100) +

  # Reside in default world
  man(qname = "reside",
      year = 2025,
      dname = "reside",
      questionText = "Where do you usually reside/live (when not in Black Rock City)?",
      questionType = "selectOne",
      responses = c("Within Nevada",
                    "Within California",
                    "Other location within the U.S.",
                    "In Canada",
                    "Other (please specify country):"),
      rname = c("Nevada",
                "California",
                "otherUS",
                "Canada",
                "otherCountry"),
      reportingValues = c(1, 2, 3, 4, 5),
      writeInResponses = "Other (please specify country):",
      wname = "otherCountry",
      writeInType = "character") +

  # ZIP code
  man(qname = "resideZIP",
      year = 2025,
      dname = "resideZIP",
      questionText = "If you usually reside in the U.S., what is your 5-digit ZIP code?",
      questionType = "textBoxNumeric",
      responses = "[0-9]{5}") +

  # Postal Code
  man(qname = "resideCAPostalCode",
      year = 2025,
      dname = "resideCAPostalCode",
      questionText = "If you usually reside in Canada, what is your postal code?",
      questionType = "textBoxCharacter",
      responses = "[A-Za-z][0-9][A-Za-z][0-9][A-Za-z][0-9]") +

  # Year attended Burning Man
  man(qname = "attendedYears",
      year = 2025,
      dname = "attendedYears",
      questionText = "Check all the years during which you attended the Burning Man event in the Black Rock Desert (or previously at Baker Beach).",
      questionType = "selectMultiple",
      responses = c("This year", as.character(2024:1991),
                    "1990 at Black Rock", "1990 at Baker Beach",
                    "1989 at Baker Beach", "1988 at Baker Beach",
                    "1987 at Baker Beach", "1986 at Baker Beach"),
      rname = c(paste0("burn", 2025:1991),
                "burn1991BlackRock", "burn1991BakerBeach",
                "burn1989", "burn1988", "burn1987", "burn1986"),
      reportingValues = c(2025:1991, 1990, 199002, 1989:1986)) +

  # Regionals attended
  man(qname = "regionalsNumberAttended",
      year = 2025,
      dname = "regionalsNumberAttended",
      questionText = "How many times have you attended a Regional Burning Man gathering?",
      questionType = "selectOne",
      responses = c("Never",
                    "Once",
                    "Multiple times"),
      rname = c("never", "once", "multipleTimes"),
      reportingValues = c(1, 2, 3)) +

  # Gender
  man(qname = "gender",
      year = 2025,
      dname = "gender",
      questionText = "What is your current gender?",
      questionType = "selectOne",
      responses = c("Female",
                    "Male",
                    "I self describe as:"),
      rname = c("female", "male", "selfDescribe"),
      reportingValues = c(1, 2, 4),
      writeInResponses = "I self describe as:",
      writeInTypes = "character") +

  # Race and ethnicity
  man(qname = "race",
      year = 2025,
      dname = "race",
      questionText = "Which category best describes your race or ethnicity?",
      questionType = "selectMultiple",
      responses = c("Native American or Alaska Native",
                    "Asian",
                    "Black or African American",
                    "Native Hawaiian or other Pacific Islander",
                    "White/Caucasian",
                    "Middle Eastern or North African",
                    "Hispanic/Latino (e.g., Mexican, Puerto Rican, Cuban, Colombian)",
                    "Other (please specify):"),
      rname = c("nativeAmericanAlaskan",
                "asian",
                "black",
                "nativeHawaiianPacificIslander",
                "white",
                "middleEasternNorthAfrican",
                "hispanic",
                "other"),
      reportingValues = c(2,1,5,8,4,7,3,6),
      writeInResponses = "Other (please specify):",
      writeInType = "character") +

  # Personal Income
  man(qname = "personalIncome",
      year = 2025,
      dname = "personalIncome",
      questionText = "What was your personal income in 2024 before taxes? Give your best estimate. Please do not include income from other household members (e.g., spouse or partner) as your own. (USD conversions are approximated based on June 2025 exchange rates)",
      questionType = "selectOne",
      responses = c("I had no personal income",
                    "Less than $7,500 USD (€6,500 / $11,500 AUD / $10,000 CAD)",
                    "$7,500-$14,999 USD (€6,500-12,999 / $11,500-22,999 AUD / $10,000-19,999 CAD)",
                    "$15,000-$24,999 USD (€13,000-21,999 / $23,000-38,999 AUD / $20,000-33,999 CAD)",
                    "$25,000-$34,999 USD (€22,000-29,999 / $39,000-53,999 AUD / $34,000-47,999 CAD)",
                    "$35,000-$49,999 USD (€30,000-42,999 / $54,000-76,999 AUD / $48,000- 67,999CAD)",
                    "$50,000-$74,999 USD (€43,000-64,999 / $77,000-115,999 AUD / $68,000-101,999 CAD)",
                    "$75,000-$99,999 USD (€65,000-86,999 / $116,000-153,999 AUD / $102,000-135,999 CAD)",
                    "$100,000-$149,999 USD (€87,000-129,999 / $154,000-230,999 AUD / $136,000-203,999 CAD)",
                    "$150,000-$299,999 USD (€130,000-259,999 / $231,000-461,999 AUD / $204,000-406,999 CAD)",
                    "$300,000-$499,999 USD (€260,000-433,999 / $462,000-769,999 AUD / $407,000-678,999 CAD)",
                    "$500,000-$999,999 USD (€434,000-866,999 / $770,000-1,539,999 AUD / $679,000-1,356,999 CAD)",
                    "$1,000,000 USD or more (€867,000+ / $1,540,000+ AUD / $1,357,000+ CAD)"),
      rname = c("PINoIncome",
                "PILessThan7500",
                "PI7500to14999",
                "PI15000to24999",
                "PI25000to34999",
                "PI35000to49999",
                "PI50000to74999",
                "PI75000to99999",
                "PI100000to149999",
                "PI150000to299999",
                "PI300000to499999",
                "PI500000to999999",
                "PI1000000orMore"),
      reportingValues = c(1:10, 18:20)) +

  # Household include others
  man(qname = "householdIncludeOthers",
      year = 2025,
      dname = "householdIncludeOthers",
      questionText = "Does your household include other people? A household consists of one or more persons who live together in the same dwelling.",
      questionType = "selectOne",
      responses = c("Yes", "No"),
      rname = c("yes", "no"),
      reportingValues = c(1,2)) +

  # Household Income
  man(qname = "householdIncome",
      year = 2025,
      dname = "householdIncome",
      questionText = "What was your total annual income before taxes of all members of your household (including you) in 2024?",
      questionType = "selectOne",
      responses = c("I had no household income",
                    "Less than $7,500 USD (€6,500 / $11,500 AUD / $10,000 CAD)",
                    "$7,500-$14,999 USD (€6,500-12,999 / $11,500-22,999 AUD / $10,000-19,999 CAD)",
                    "$15,000-$24,999 USD (€13,000-21,999 / $23,000-38,999 AUD / $20,000-33,999 CAD)",
                    "$25,000-$34,999 USD (€22,000-29,999 / $39,000-53,999 AUD / $34,000-47,999 CAD)",
                    "$35,000-$49,999 USD (€30,000-42,999 / $54,000-76,999 AUD / $48,000- 67,999CAD)",
                    "$50,000-$74,999 USD (€43,000-64,999 / $77,000-115,999 AUD / $68,000-101,999 CAD)",
                    "$75,000-$99,999 USD (€65,000-86,999 / $116,000-153,999 AUD / $102,000-135,999 CAD)",
                    "$100,000-$149,999 USD (€87,000-129,999 / $154,000-230,999 AUD / $136,000-203,999 CAD)",
                    "$150,000-$299,999 USD (€130,000-259,999 / $231,000-461,999 AUD / $204,000-406,999 CAD)",
                    "$300,000-$499,999 USD (€260,000-433,999 / $462,000-769,999 AUD / $407,000-678,999 CAD)",
                    "$500,000-$999,999 USD (€434,000-866,999 / $770,000-1,539,999 AUD / $679,000-1,356,999 CAD)",
                    "$1,000,000 USD or more (€867,000+ / $1,540,000+ AUD / $1,357,000+ CAD)"),
      rname = c("PINoIncome",
                "PILessThan7500",
                "PI7500to14999",
                "PI15000to24999",
                "PI25000to34999",
                "PI35000to49999",
                "PI50000to74999",
                "PI75000to99999",
                "PI100000to149999",
                "PI150000to299999",
                "PI300000to499999",
                "PI500000to999999",
                "PI1000000orMore"),
      reportingValues = c(1:10, 18:20)) +

  # Education
  man(qname = "education",
      year = 2025,
      dname = "education",
      questionText = "What is the highest level of education you have completed?",
      questionType = "selectOne",
      responses = c("Did not complete high school/secondary school",
                    "High school/secondary school",
                    "Technical/vocational certificate or trade school",
                    "Some college/university (select if degree not completed)",
                    "Associate's degree from college/university",
                    "Bachelor's degree from college/university",
                    "Master's degree from college/university (e.g., MA, MS, MPH)",
                    "Doctorate degree from college/university (e.g., PhD, MD, JD)",
                    "Graduate degree (Master's, Doctorate, or equivalent) or equivalent",
                    "Other (please specify):",
                    "None of the above"),
      rname = c("lessThanHighSchool",
                "highSchool",
                "technicalVocational",
                "someCollege",
                "associates",
                "bachelors",
                "masters",
                "doctorate",
                "graduate",
                "other",
                "none"),
      reportingValues = c(12, 13, 18, 14, 15, 16, 23, 24, 17, 19, 20),
      writeInResponses = "Other (please specify):",
      writeInTypes = "character") +

  # Voted in last election
  man(qname = "voteInLastElection",
      year = 2025,
      dname = "voteInLastElection",
      questionText = "Did you vote in the last federal/national election in your primary country of residence?",
      questionType = "selectOne",
      responses = c("Yes", "No", "I am not eligible"),
      rname = c("yes", "no", "notEligible"),
      reportingValues = c(1,2,3)) +

  # Ticket sale
  man(qname = "ticketSale",
      year = 2025,
      dname = "ticketSale",
      questionText = "In which sale did you purchase your ticket?",
      questionType = "selectOne",
      responses = c("Standard ticket (e.g., Today sale, Tomorrow sale, OMG Sale, Secure Ticket Exchange Program (STEP), Ticket Aid Program, Resilience Program, Renaissance Program, through a friend or third party)",
                    "Stewards sale (e.g., directed group sale through a theme camp, art installation, mutant vehicle, or special project)",
                    "Staff credentials or volunteer ticket (gift, discounted or full-price) through a Burning Man department",
                    "Other"),
      rname = c("standardTicket",
                "stewardsSale",
                "staffOrVolunteer",
                "other"),
      reportingValues = c(1,2,3,4)) +

  # Voted in last four elections
  man(qname = "voteLastFourUS",
      year = 2025,
      dname = "voteLastFourUS",
      questionText = "In which of the last four Federal US elections did you vote?",
      questionType = "selectMultiple",
      responses = c("2024", "2022", "2020", "2018", "None", "I'm not eligible"),
      rname = c("vote2024", "vote2022", "vote2020", "vote2018",
                "none", "notEligible"),
      reportingValues = c(10, 9, 8, 7, 5, 11)) +

  # Political Party
  man(qname = "politicalPartyUS",
      year = 2025,
      dname = "politicalPartyUS",
      questionText = "With which political party are you currently affiliated in the United States, if any?",
      questionType = "selectOne",
      responses = c("Democratic Party",
                    "Green Party",
                    "Libertarian Party",
                    "Republican Party",
                    "Other US based political party (please specify)",
                    "None, I am nonpartisan",
                    "None, I choose to remain unaffiliated (or nonpartisan)",
                    "I prefer not to state"),
      rname = c("democratic",
                "green",
                "libertarian",
                "republican",
                "otherUSPoliticalParty",
                "nonpartisan",
                "noneUnaffiliated",
                "preferNotToState"),
      reportingValues = c(1,4,3,2,6,8,7,9),
      writeInResponses = "Other US based political party (please specify)",
      writeInTypes = "character") +

  # Political views
  man(qname = "politicalViews",
      year = 2025,
      dname = "politicalViews",
      questionText = "Generally, in terms of political views, rather than political parties, I consider myself to be primarily... Check one or two.",
      questionType = "selectMultiple",
      responses = c("Anarchist",
                    "Conservative",
                    "Green and/or Environmental",
                    "Liberal",
                    "Libertarian",
                    "Moderate and/or Centrist",
                    "Progressive",
                    "Socialist",
                    "Other (please specify):",
                    "None, I consider myself to be apolitical",
                    "I prefer not to state"),
      rname = c("anarchist",
                "conservative",
                "green",
                "liberal",
                "libertarian",
                "moderate",
                "progressive",
                "socialist",
                "other",
                "noneApolitical",
                "preferNotToState"),
      reportingValues = c(1,2,3,4,5,10,6,7,8,9,11),
      writeInResponses = "Other (please specify):",
      writeInTypes = "character") +

  # Language
  man(qname = "language",
      year = 2025,
      dname = "language",
      questionText = "What was the first language you learned and still use (i.e., your native language)?",
      questionType = "selectOne",
      responses = c("English",
                    "Arabic",
                    "Chinese",
                    "Danish",
                    "Dutch",
                    "Farsi",
                    "French",
                    "German",
                    "Hebrew",
                    "Hindi",
                    "Italian",
                    "Japanese",
                    "Norwegian",
                    "Polish",
                    "Portuguese",
                    "Punjabi",
                    "Romanian",
                    "Russian",
                    "Spanish",
                    "Swedish",
                    "Tagalog",
                    "Urdu",
                    "Other (please specify):"),
      rname = c("english",
                "arabic",
                "chinese",
                "danish",
                "dutch",
                "farsi",
                "french",
                "german",
                "hebrew",
                "hindi",
                "italian",
                "japanese",
                "norwegian",
                "polish",
                "portuguese",
                "punjabi",
                "romanian",
                "russian",
                "spanish",
                "swedish",
                "tagalog",
                "urdu",
                "other"),
      reportingValues = c(1:23),
      writeInResponses = "Other (please specify):",
      writeInTypes = "character") +

  # Spirituality
  man(qname = "spirituality",
      year = 2025,
      dname = "spirituality",
      questionText = "How do you describe your spirituality?",
      questionType = "selectOne",
      responses = c("I am religious",
                    "I am spiritual but not religious",
                    "I am atheist",
                    "I am agnostic",
                    "I am deist",
                    "I don't know"),
      rname = c("reigious",
                "spiritual",
                "atheist",
                "agnostic",
                "deist",
                "dontKnow"),
      reportingValues = c(1,2,3,4,5,6)) +

  # Sexual orientation
  man(qname = "sexualOrientation",
      year = 2025,
      dname = "sexualOrientation",
      questionText = "Which of these expressions best describes your sexual orientation?",
      questionType = "selectOne",
      responses = c("Heterosexual or straight",
                    "Gay, lesbian, or homosexual",
                    "Bisexual or pansexual",
                    "Bicurious or heteroflexible",
                    "Asexual",
                    "I refuse to use labels to describe my sexual orientation",
                    "I self-describe as:"),
      rname = c("heterosexualStraight",
                "gayLesbianHomosexual",
                "bisexualPansexual",
                "bicuriousHeteroflexible",
                "asexual",
                "refuseToLabel",
                "selfDescribe"),
      reportingValues = c(1,2,3,4,5,6,8),
      writeInResponses = "I self-describe as:",
      writeInTypes = "character") +

  # Gender Identity
  man(qname = "genderIdentity",
      year = 2025,
      dname = "genderIdentity",
      questionText = "Do you consider yourself to be non-binary, transgender, genderqueer, gender non-conforming, gender questioning, or two-spirit?",
      questionType = "selectOne",
      responses = c("Yes", "No"),
      rname = c("yes", "no"),
      reportingValues = c(1, 2)) +

  # Default world partner
  man(qname = "partner",
      year = 2025,
      dname = "partner",
      questionText = "In the default world, do you have a partner or partners?",
      questionType = "selectOne",
      responses = c("Yes, and I am married to my partner (or to one of my partners)",
                    "Yes, and we are not married",
                    "No",
                    "It's complicated"),
      rname = c("yesMarried",
                "yesNotMarried",
                "no",
                "itsComplicated"),
      reportingValues = c(1,2,3,4)) +

  # Any pets
  man(qname = "petsAny",
      year = 2025,
      dname = "petsAny",
      questionText = "In the default world, do you have any pets?",
      questionType = "selectOne",
      responses = c("Yes, I have multiple pets",
                    "Yes, I have only one pet",
                    "No",
                    "It's complicated"),
      rname = c("yesMultiple",
                "yesOne",
                "no",
                "itsComplicated"),
      reportingValues = c(1,2,3,4)) +

  #
  man(qname = "petsWhatKind",
      year = 2025,
      dname = "petsWhatKind",
      questionText = "What kind of pet(s) do you have? Check all that apply.",
      questionType = "selectMultiple",
      responses = c("Cats",
                    "Dogs",
                    "Birds and/or poultry",
                    "Fish and/or crustaceans",
                    "Rabbits and/or rodents",
                    "Reptiles and/or amphibians",
                    "Insects and/or arachnids",
                    "Goats and/or sheep",
                    "Horses",
                    "Other farm animals (please specify):",
                    "Other (please specify):"),
      rname = c("cats",
                "dogs",
                "birdsPoultry",
                "fishCrustaceans",
                "rabbitsRodents",
                "reptilesAmphibians",
                "instectsArachnids",
                "goatsSheep",
                "horses",
                "otherFarmAnimals",
                "other"),
      reportingValues = c(1:11),
      writeInResponses = c("Other farm animals (please specify):",
                           "Other (please specify):"),
      writeInTypes = c("character", "character")) +

  # Media managed by Burning Man Project
  man(qname = "mediaManagedByBMP",
      year = 2025,
      dname = "mediaManagedByBMP",
      questionText = "Which of the following media managed by Burning Man Project do you use to receive news, information, and events related to Burning Man, and to engage in discussion on Burning Man topics?",
      questionType = "selectScale",
      responses = c("Jack Rabbit Speaks (JRS) e-newsletter",
                    "Burning Man website",
                    "Burning Man Journal",
                    "Burning Man Hive",
                    "Social media managed by Burning Man Project (Facebook, Instagram, Twitter/X, YouTube, etc.)",
                    "Eplaya"),
      scaleOptions = c("Never", "Rarely", "Often"),
      reportingValues = c(1, 2, 3),
      rname = c("jackrabbitSpeaks",
                "burningManWebsite",
                "burningManJournal",
                "burningManHive",
                "socialMedia",
                "ePlaya")) +

  # Preparation
  man(qname = "preparationResourcesFromBMP",
      year = 2025,
      dname = "preparationResourcesFromBMP",
      questionText = "Which of the following Burning Man Project resources helped you prepare for Black Rock City? Check all that apply.",
      questionType = "selectMultiple",
      responses = c("Survival Guide booklet",
                    "Online Survival Guide",
                    "Burningman.org website",
                    "Burning Man Instagram",
                    "Burning Man Facebook",
                    "Burning Man TikTok",
                    "Burning Man YouTube channel",
                    "Burning Man Journal (blog)",
                    "Burning Man LIVE podcast",
                    "Jackrabbit Speaks (JRS) newsletter",
                    "Burning Man HIVE",
                    "Other (specify):"),
      rname = c("survivalGuideBooklet",
                "onlineSurvivalGuide",
                "website",
                "instagram",
                "facebook",
                "tiktok",
                "youtube",
                "journal",
                "LIVEPodcast",
                "jackrabbitSpeaks",
                "HIVE",
                "other"),
      reportingValues = c(1,2,13:22),
      writeInResponses = "Other (specify):",
      writeInTypes = "character") +

  #
  man(qname = "valuableInformationFromBMP",
      year = 2025,
      dname = "valuableInformationFromBMP",
      questionText = "What types of information do you find most valuable coming from Burning Man Project?",
      questionType = "selectMultiple",
      responses = c("Events, gatherings, and things to do in Black Rock City",
                    "Bay Area events",
                    "Events in cities around the country and around the world",
                    "Burning Man Regional events",
                    "Volunteer opportunities with established teams/departments (Rangers, Gate, Greeters, etc.)",
                    "Opportunities to create and/or assist with art (or other artistic endeavors)",
                    "Black Rock City event preparation information",
                    "Information about camps offering activities and/or seeking members",
                    "Photos/videos from Black Rock City",
                    "Stories about Burners around the world",
                    "Information about Burning Man Project's nonprofit programs",
                    "Information about supporting Radical Inclusion, Diversity, and Equity in the Burning Man community",
                    "Resources about environmental sustainability as it relates to Burning Man",
                    "Other (please specify):"),
      rname = c("eventsInBRC",
                "bayAreaEvents",
                "eventsInOtherCities",
                "regionals",
                "volunteerOpportunities",
                "artOpportunities",
                "preparationInformation",
                "campInformation",
                "photosFromBRC",
                "storiesAboutBurners",
                "nonProfitInformation",
                "RIDEInformation",
                "sustainability",
                "other"),
      reportingValues = c(1,2,3,4,5,11,6,12,7,8,9,13,14,10),
      writeInResponses = "Other (please specify):") +

  #
  man(qname = "",
      year = 2025,
      dname = "",
      questionText = "",
      questionType = "",
      responses = c(),
      rname = c(),
      reportingValues = c()) +


