
#Virgin
man2025 <- man(qname = "virgin",
               year = 2025,
               dname = "virgin",
               questionText = "Was this your first time visiting Black Rock City?",
               questionType = "selectOne",
               responses = c("Yes, it was my first time",
                             "No, I have been to Black Rock City before",
                             "I did not go to Black Rock City in 2025"),
               rname = c("virgin",
                         "notVirgin",
                         "didNotGoIn2025"),
               reportingValues = c(1, 2, 3)) +

  # Presently at BRC
  man(qname = "atBRC",
      year = 2025,
      dname = "atBRC",
      questionText = "Are you presently at Black Rock City?",
      questionType = "selectOne",
      responses = c("No, I left",
                    "Yes, I am still there",
                    "Yes, but the event is over"),
      rname = c("no",
                "yesStillThere",
                "yesEventOver"),
      reportingValues = c(1, 2, 3)) +

  # Age
  man(qname = "age",
      year = 2025,
      dname = "age",
      questionText = "What was your age when you ARRIVED at Black Rock City this year?",
      questionType = "selectOne",
      responses = as.character(1:100),
      rname = paste0("age", 1:100),
      reportingValues = 1:100) +

  # Reside in default world
  man(qname = "reside",
      year = 2025,
      dname = "reside",
      questionText = "Where do you usually reside/live (when not in Black Rock City)?",
      questionType = "selectOne",
      responses = c("Within Nevada",
                    "Within California",
                    "Other location within the U.S.",
                    "In Canada",
                    "Other (please specify country):"),
      rname = c("Nevada",
                "California",
                "otherUS",
                "Canada",
                "otherCountry"),
      reportingValues = c(1, 2, 3, 4, 5),
      writeIn = c(otherCountry = "character")) +

  # ZIP code
  man(qname = "resideZIP",
      year = 2025,
      dname = "resideZIP",
      questionText = "If you usually reside in the U.S., what is your 5-digit ZIP code?",
      questionType = "textBoxNumeric",
      responses = "[0-9]{5}") +

  # Postal Code
  man(qname = "resideCAPostalCode",
      year = 2025,
      dname = "resideCAPostalCode",
      questionText = "If you usually reside in Canada, what is your postal code?",
      questionType = "textBoxCharacter",
      responses = "[A-Za-z][0-9][A-Za-z][0-9][A-Za-z][0-9]") +

  # Year attended Burning Man
  man(qname = "attendedYears",
      year = 2025,
      dname = "attendedYears",
      questionText = "Check all the years during which you attended the Burning Man event in the Black Rock Desert (or previously at Baker Beach).",
      questionType = "selectMultiple",
      responses = c("This year", as.character(2024:1991),
                    "1990 at Black Rock", "1990 at Baker Beach",
                    "1989 at Baker Beach", "1988 at Baker Beach",
                    "1987 at Baker Beach", "1986 at Baker Beach"),
      rname = c(paste0("burn", 2025:1991),
                "burn1991BlackRock", "burn1991BakerBeach",
                "burn1989", "burn1988", "burn1987", "burn1986"),
      reportingValues = c(2025:1991, 1990, 199002, 1989:1986)) +

  # Regionals attended
  man(qname = "regionalsNumberAttended",
      year = 2025,
      dname = "regionalsNumberAttended",
      questionText = "How many times have you attended a Regional Burning Man gathering?",
      questionType = "selectOne",
      responses = c("Never",
                    "Once",
                    "Multiple times"),
      rname = c("never", "once", "multipleTimes"),
      reportingValues = c(1, 2, 3)) +

  # Gender
  man(qname = "gender",
      year = 2025,
      dname = "gender",
      questionText = "What is your current gender?",
      questionType = "selectOne",
      responses = c("Female",
                    "Male",
                    "I self describe as:"),
      rname = c("female", "male", "selfDescribe"),
      reportingValues = c(1, 2, 4),
      writeIn = c(selfDescribe = "character")) +

  # Race and ethnicity
  man(qname = "race",
      year = 2025,
      dname = "race",
      questionText = "Which category best describes your race or ethnicity?",
      questionType = "selectMultiple",
      responses = c("Native American or Alaska Native",
                    "Asian",
                    "Black or African American",
                    "Native Hawaiian or other Pacific Islander",
                    "White/Caucasian",
                    "Middle Eastern or North African",
                    "Hispanic/Latino (e.g., Mexican, Puerto Rican, Cuban, Colombian)",
                    "Other (please specify):"),
      rname = c("nativeAmericanAlaskan",
                "asian",
                "black",
                "nativeHawaiianPacificIslander",
                "white",
                "middleEasternNorthAfrican",
                "hispanic",
                "other"),
      reportingValues = c(2,1,5,8,4,7,3,6),
      writeIn = c(other = "character")) +

  # Personal Income
  man(qname = "personalIncome",
      year = 2025,
      dname = "personalIncome",
      questionText = "What was your personal income in 2024 before taxes? Give your best estimate. Please do not include income from other household members (e.g., spouse or partner) as your own. (USD conversions are approximated based on June 2025 exchange rates)",
      questionType = "selectOne",
      responses = c("I had no personal income",
                    "Less than $7,500 USD (€6,500 / $11,500 AUD / $10,000 CAD)",
                    "$7,500-$14,999 USD (€6,500-12,999 / $11,500-22,999 AUD / $10,000-19,999 CAD)",
                    "$15,000-$24,999 USD (€13,000-21,999 / $23,000-38,999 AUD / $20,000-33,999 CAD)",
                    "$25,000-$34,999 USD (€22,000-29,999 / $39,000-53,999 AUD / $34,000-47,999 CAD)",
                    "$35,000-$49,999 USD (€30,000-42,999 / $54,000-76,999 AUD / $48,000- 67,999CAD)",
                    "$50,000-$74,999 USD (€43,000-64,999 / $77,000-115,999 AUD / $68,000-101,999 CAD)",
                    "$75,000-$99,999 USD (€65,000-86,999 / $116,000-153,999 AUD / $102,000-135,999 CAD)",
                    "$100,000-$149,999 USD (€87,000-129,999 / $154,000-230,999 AUD / $136,000-203,999 CAD)",
                    "$150,000-$299,999 USD (€130,000-259,999 / $231,000-461,999 AUD / $204,000-406,999 CAD)",
                    "$300,000-$499,999 USD (€260,000-433,999 / $462,000-769,999 AUD / $407,000-678,999 CAD)",
                    "$500,000-$999,999 USD (€434,000-866,999 / $770,000-1,539,999 AUD / $679,000-1,356,999 CAD)",
                    "$1,000,000 USD or more (€867,000+ / $1,540,000+ AUD / $1,357,000+ CAD)"),
      rname = c("PINoIncome",
                "PILessThan7500",
                "PI7500to14999",
                "PI15000to24999",
                "PI25000to34999",
                "PI35000to49999",
                "PI50000to74999",
                "PI75000to99999",
                "PI100000to149999",
                "PI150000to299999",
                "PI300000to499999",
                "PI500000to999999",
                "PI1000000orMore"),
      reportingValues = c(1:10, 18:20)) +

  # Household include others
  man(qname = "householdIncludeOthers",
      year = 2025,
      dname = "householdIncludeOthers",
      questionText = "Does your household include other people? A household consists of one or more persons who live together in the same dwelling.",
      questionType = "selectOne",
      responses = c("Yes", "No"),
      rname = c("yes", "no"),
      reportingValues = c(1,2)) +

  # Household Income
  man(qname = "householdIncome",
      year = 2025,
      dname = "householdIncome",
      questionText = "What was your total annual income before taxes of all members of your household (including you) in 2024?",
      questionType = "selectOne",
      responses = c("I had no household income",
                    "Less than $7,500 USD (€6,500 / $11,500 AUD / $10,000 CAD)",
                    "$7,500-$14,999 USD (€6,500-12,999 / $11,500-22,999 AUD / $10,000-19,999 CAD)",
                    "$15,000-$24,999 USD (€13,000-21,999 / $23,000-38,999 AUD / $20,000-33,999 CAD)",
                    "$25,000-$34,999 USD (€22,000-29,999 / $39,000-53,999 AUD / $34,000-47,999 CAD)",
                    "$35,000-$49,999 USD (€30,000-42,999 / $54,000-76,999 AUD / $48,000- 67,999CAD)",
                    "$50,000-$74,999 USD (€43,000-64,999 / $77,000-115,999 AUD / $68,000-101,999 CAD)",
                    "$75,000-$99,999 USD (€65,000-86,999 / $116,000-153,999 AUD / $102,000-135,999 CAD)",
                    "$100,000-$149,999 USD (€87,000-129,999 / $154,000-230,999 AUD / $136,000-203,999 CAD)",
                    "$150,000-$299,999 USD (€130,000-259,999 / $231,000-461,999 AUD / $204,000-406,999 CAD)",
                    "$300,000-$499,999 USD (€260,000-433,999 / $462,000-769,999 AUD / $407,000-678,999 CAD)",
                    "$500,000-$999,999 USD (€434,000-866,999 / $770,000-1,539,999 AUD / $679,000-1,356,999 CAD)",
                    "$1,000,000 USD or more (€867,000+ / $1,540,000+ AUD / $1,357,000+ CAD)"),
      rname = c("PINoIncome",
                "PILessThan7500",
                "PI7500to14999",
                "PI15000to24999",
                "PI25000to34999",
                "PI35000to49999",
                "PI50000to74999",
                "PI75000to99999",
                "PI100000to149999",
                "PI150000to299999",
                "PI300000to499999",
                "PI500000to999999",
                "PI1000000orMore"),
      reportingValues = c(1:10, 18:20)) +

  # Education
  man(qname = "education",
      year = 2025,
      dname = "education",
      questionText = "What is the highest level of education you have completed?",
      questionType = "selectOne",
      responses = c("Did not complete high school/secondary school",
                    "High school/secondary school",
                    "Technical/vocational certificate or trade school",
                    "Some college/university (select if degree not completed)",
                    "Associate's degree from college/university",
                    "Bachelor's degree from college/university",
                    "Master's degree from college/university (e.g., MA, MS, MPH)",
                    "Doctorate degree from college/university (e.g., PhD, MD, JD)",
                    "Graduate degree (Master's, Doctorate, or equivalent) or equivalent",
                    "Other (please specify):",
                    "None of the above"),
      rname = c("lessThanHighSchool", c(), #TODO
                "highSchool",
                "technicalVocational",
                "someCollege",
                "associates",
                "bachelors",
                "masters",
                "doctorate",
                "graduate",
                "other",
                "none"),
      reportingValues = c(12, 13, 18, 14, 15, 16, 23, 24, 17, 19, 20),
      writeIn = c(other = "character")) +

  # Voted in last election
  man(qname = "voteInLastElection",
      year = 2025,
      dname = "voteInLastElection",
      questionText = "Did you vote in the last federal/national election in your primary country of residence?",
      questionType = "selectOne",
      responses = c("Yes", "No", "I am not eligible"),
      rname = c("yes", "no", "notEligible"),
      reportingValues = c(1,2,3)) +

  # Ticket sale
  man(qname = "ticketSale",
      year = 2025,
      dname = "ticketSale",
      questionText = "In which sale did you purchase your ticket?",
      questionType = "selectOne",
      responses = c("Standard ticket (e.g., Today sale, Tomorrow sale, OMG Sale, Secure Ticket Exchange Program (STEP), Ticket Aid Program, Resilience Program, Renaissance Program, through a friend or third party)",
                    "Stewards sale (e.g., directed group sale through a theme camp, art installation, mutant vehicle, or special project)",
                    "Staff credentials or volunteer ticket (gift, discounted or full-price) through a Burning Man department",
                    "Other"),
      rname = c("standardTicket",
                "stewardsSale",
                "staffOrVolunteer",
                "other"),
      reportingValues = c(1,2,3,4)) +

  # Voted in last four elections
  man(qname = "voteLastFourUS",
      year = 2025,
      dname = "voteLastFourUS",
      questionText = "In which of the last four Federal US elections did you vote?",
      questionType = "selectMultiple",
      responses = c("2024", "2022", "2020", "2018", "None", "I'm not eligible"),
      rname = c("vote2024", "vote2022", "vote2020", "vote2018",
                "none", "notEligible"),
      reportingValues = c(10, 9, 8, 7, 5, 11)) +

  # Political Party
  man(qname = "politicalPartyUS",
      year = 2025,
      dname = "politicalPartyUS",
      questionText = "With which political party are you currently affiliated in the United States, if any?",
      questionType = "selectOne",
      responses = c("Democratic Party",
                    "Green Party",
                    "Libertarian Party",
                    "Republican Party",
                    "Other US based political party (please specify)",
                    "None, I am nonpartisan",
                    "None, I choose to remain unaffiliated (or nonpartisan)",
                    "I prefer not to state"),
      rname = c("democratic",
                "green",
                "libertarian",
                "republican",
                "otherUSPoliticalParty",
                "nonpartisan",
                "noneUnaffiliated",
                "preferNotToState"),
      reportingValues = c(1,4,3,2,6,8,7,9),
      writeIn = c(otherUSPoliticalParty = "character")) +

  # Political views
  man(qname = "politicalViews",
      year = 2025,
      dname = "politicalViews",
      questionText = "Generally, in terms of political views, rather than political parties, I consider myself to be primarily... Check one or two.",
      questionType = "selectMultiple",
      responses = c("Anarchist",
                    "Conservative",
                    "Green and/or Environmental",
                    "Liberal",
                    "Libertarian",
                    "Moderate and/or Centrist",
                    "Progressive",
                    "Socialist",
                    "Other (please specify):",
                    "None, I consider myself to be apolitical",
                    "I prefer not to state"),
      rname = c("anarchist",
                "conservative",
                "green",
                "liberal",
                "libertarian",
                "moderate",
                "progressive",
                "socialist",
                "other",
                "noneApolitical",
                "preferNotToState"),
      reportingValues = c(1,2,3,4,5,10,6,7,8,9,11),
      writeIn = c(other = "character")) +

  # Language
  man(qname = "language",
      year = 2025,
      dname = "language",
      questionText = "What was the first language you learned and still use (i.e., your native language)?",
      questionType = "selectOne",
      responses = c("English",
                    "Arabic",
                    "Chinese",
                    "Danish",
                    "Dutch",
                    "Farsi",
                    "French",
                    "German",
                    "Hebrew",
                    "Hindi",
                    "Italian",
                    "Japanese",
                    "Norwegian",
                    "Polish",
                    "Portuguese",
                    "Punjabi",
                    "Romanian",
                    "Russian",
                    "Spanish",
                    "Swedish",
                    "Tagalog",
                    "Urdu",
                    "Other (please specify):"),
      rname = c("english",
                "arabic",
                "chinese",
                "danish",
                "dutch",
                "farsi",
                "french",
                "german",
                "hebrew",
                "hindi",
                "italian",
                "japanese",
                "norwegian",
                "polish",
                "portuguese",
                "punjabi",
                "romanian",
                "russian",
                "spanish",
                "swedish",
                "tagalog",
                "urdu",
                "other"),
      reportingValues = c(1:23),
      writeIn = c(other = "character")) +

  # Spirituality
  man(qname = "spirituality",
      year = 2025,
      dname = "spirituality",
      questionText = "How do you describe your spirituality?",
      questionType = "selectOne",
      responses = c("I am religious",
                    "I am spiritual but not religious",
                    "I am atheist",
                    "I am agnostic",
                    "I am deist",
                    "I don't know"),
      rname = c("reigious",
                "spiritual",
                "atheist",
                "agnostic",
                "deist",
                "dontKnow"),
      reportingValues = c(1,2,3,4,5,6)) +

  # Sexual orientation
  man(qname = "sexualOrientation",
      year = 2025,
      dname = "sexualOrientation",
      questionText = "Which of these expressions best describes your sexual orientation?",
      questionType = "selectOne",
      responses = c("Heterosexual or straight",
                    "Gay, lesbian, or homosexual",
                    "Bisexual or pansexual",
                    "Bicurious or heteroflexible",
                    "Asexual",
                    "I refuse to use labels to describe my sexual orientation",
                    "I self-describe as:"),
      rname = c("heterosexualStraight",
                "gayLesbianHomosexual",
                "bisexualPansexual",
                "bicuriousHeteroflexible",
                "asexual",
                "refuseToLabel",
                "selfDescribe"),
      reportingValues = c(1,2,3,4,5,6,8),
      writeIn = c(selfDescribe = "character")) +

  # Gender Identity
  man(qname = "genderIdentity",
      year = 2025,
      dname = "genderIdentity",
      questionText = "Do you consider yourself to be non-binary, transgender, genderqueer, gender non-conforming, gender questioning, or two-spirit?",
      questionType = "selectOne",
      responses = c("Yes", "No"),
      rname = c("yes", "no"),
      reportingValues = c(1, 2)) +

  # Default world partner
  man(qname = "partner",
      year = 2025,
      dname = "partner",
      questionText = "In the default world, do you have a partner or partners?",
      questionType = "selectOne",
      responses = c("Yes, and I am married to my partner (or to one of my partners)",
                    "Yes, and we are not married",
                    "No",
                    "It's complicated"),
      rname = c("yesMarried",
                "yesNotMarried",
                "no",
                "itsComplicated"),
      reportingValues = c(1,2,3,4)) +

  # Any pets
  man(qname = "petsAny",
      year = 2025,
      dname = "petsAny",
      questionText = "In the default world, do you have any pets?",
      questionType = "selectOne",
      responses = c("Yes, I have multiple pets",
                    "Yes, I have only one pet",
                    "No",
                    "It's complicated"),
      rname = c("yesMultiple",
                "yesOne",
                "no",
                "itsComplicated"),
      reportingValues = c(1,2,3,4)) +

  #
  man(qname = "petsWhatKind",
      year = 2025,
      dname = "petsWhatKind",
      questionText = "What kind of pet(s) do you have? Check all that apply.",
      questionType = "selectMultiple",
      responses = c("Cats",
                    "Dogs",
                    "Birds and/or poultry",
                    "Fish and/or crustaceans",
                    "Rabbits and/or rodents",
                    "Reptiles and/or amphibians",
                    "Insects and/or arachnids",
                    "Goats and/or sheep",
                    "Horses",
                    "Other farm animals (please specify):",
                    "Other (please specify):"),
      rname = c("cats",
                "dogs",
                "birdsPoultry",
                "fishCrustaceans",
                "rabbitsRodents",
                "reptilesAmphibians",
                "instectsArachnids",
                "goatsSheep",
                "horses",
                "otherFarmAnimals",
                "otherPetTypes"),
      reportingValues = c(1:11),
      writeIn = c(otherFarmAnimals = "character",
                  otherPetTypes = "character")) +

  # Media managed by Burning Man Project
  man(qname = "mediaManagedByBMP",
      year = 2025,
      dname = "mediaManagedByBMP",
      questionText = "Which of the following media managed by Burning Man Project do you use to receive news, information, and events related to Burning Man, and to engage in discussion on Burning Man topics?",
      questionType = "selectScale",
      responses = c("Jack Rabbit Speaks (JRS) e-newsletter",
                    "Burning Man website",
                    "Burning Man Journal",
                    "Burning Man Hive",
                    "Social media managed by Burning Man Project (Facebook, Instagram, Twitter/X, YouTube, etc.)",
                    "Eplaya"),
      scaleOptions = c("Never", "Rarely", "Often"),
      reportingValues = c(1, 2, 3),
      rname = c("jackrabbitSpeaks",
                "burningManWebsite",
                "burningManJournal",
                "burningManHive",
                "socialMedia",
                "ePlaya")) +

  # Preparation
  man(qname = "preparationResourcesFromBMP",
      year = 2025,
      dname = "preparationResourcesFromBMP",
      questionText = "Which of the following Burning Man Project resources helped you prepare for Black Rock City? Check all that apply.",
      questionType = "selectMultiple",
      responses = c("Survival Guide booklet",
                    "Online Survival Guide",
                    "Burningman.org website",
                    "Burning Man Instagram",
                    "Burning Man Facebook",
                    "Burning Man TikTok",
                    "Burning Man YouTube channel",
                    "Burning Man Journal (blog)",
                    "Burning Man LIVE podcast",
                    "Jackrabbit Speaks (JRS) newsletter",
                    "Burning Man HIVE",
                    "Other (specify):"),
      rname = c("survivalGuideBooklet",
                "onlineSurvivalGuide",
                "website",
                "instagram",
                "facebook",
                "tiktok",
                "youtube",
                "journal",
                "LIVEPodcast",
                "jackrabbitSpeaks",
                "HIVE",
                "other"),
      reportingValues = c(1,2,13:22),
      writeIn = c(other = "character")) +

  #
  man(qname = "valuableInformationFromBMP",
      year = 2025,
      dname = "valuableInformationFromBMP",
      questionText = "What types of information do you find most valuable coming from Burning Man Project?",
      questionType = "selectMultiple",
      responses = c("Events, gatherings, and things to do in Black Rock City",
                    "Bay Area events",
                    "Events in cities around the country and around the world",
                    "Burning Man Regional events",
                    "Volunteer opportunities with established teams/departments (Rangers, Gate, Greeters, etc.)",
                    "Opportunities to create and/or assist with art (or other artistic endeavors)",
                    "Black Rock City event preparation information",
                    "Information about camps offering activities and/or seeking members",
                    "Photos/videos from Black Rock City",
                    "Stories about Burners around the world",
                    "Information about Burning Man Project's nonprofit programs",
                    "Information about supporting Radical Inclusion, Diversity, and Equity in the Burning Man community",
                    "Resources about environmental sustainability as it relates to Burning Man",
                    "Other (please specify):"),
      rname = c("eventsInBRC",
                "bayAreaEvents",
                "eventsInOtherCities",
                "regionals",
                "volunteerOpportunities",
                "artOpportunities",
                "preparationInformation",
                "campInformation",
                "photosFromBRC",
                "storiesAboutBurners",
                "nonProfitInformation",
                "RIDEInformation",
                "sustainability",
                "other"),
      reportingValues = c(1,2,3,4,5,11,6,12,7,8,9,13,14,10),
      writeIn = c(other = "character")) +

  # Radio
  man(qname = "radio",
      year = 2025,
      dname = "radio",
      questionText = "Which radio station did you listen to on playa this year? Check all that apply.",
      questionType = "selectMultiple",
      responses = c("BMIR (Burning Man Information Radio) 94.5 FM",
                    "GARS (Gate Advisory Radio Station) 95.1 FM",
                    "Other (specify):",
                    "None"),
      rname = c("BMIR",
                "GARS",
                "other",
                "none"),
      reportingValues = c(1,2,4,5),
      writeIn = c(other = "character")) +

  # Devices Used
  man(qname = "devicesUsedAtBRC",
      year = 2025,
      dname = "devicesUsedAtBRC",
      questionText = "Did you use any devices during your time at Black Rock City for the following purpose? Select one answer per row.",
      questionType = "selectScale",
      responses = c("Using third-party BRC apps (e.g., Dust, iBurn)",
                    "Accessing the BRC Dashboard webpage",
                    "Content capture (photo, video, or audio)",
                    "Sharing content to social media",
                    "Browsing social media",
                    "Contacting fellow Burners at Black Rock City",
                    "Contacting people outside of Black Rock City",
                    "Checking work emails",
                    "Checking personal emails",
                    "Saving information of new connections",
                    "Playing music",
                    "Streaming videos or movies",
                    "Reading news"),
      rname = c("thirdPartyBRCApp",
                "BRCDashboard",
                "contentCapture",
                "sharingSocialMedia",
                "browsingSocialMedia",
                "contactBurnersAtBRC",
                "contactPeopleOutsideBRC",
                "checkWorkEmails",
                "checkPersonalEmails",
                "saveNewConnections",
                "playMusic",
                "streamVideosMovies",
                "readNews"),
      scaleOptions = c("Never",
                       "Less than once per day",
                       "About once a day",
                       "More than once a day"),
      reportingValues = c(1,2,5,6)) +

  # Applications used at Burning Man
  man(qname = "applicationsUsedAtBRC",
      year = 2025,
      dname = "applicationsUsedAtBRC",
      questionText = "Did you use any devices during your time at Black Rock City for the following purpose? Select one answer per row.",
      questionType = "selectMultiple",
      responses = c("Communication apps (e.g., email, TXT, Messenger, WhatsApp, Discord, Signal, Telegram, Slack, Zoom, Teams)",
                    "Social media apps",
                    "Audio streaming apps",
                    "Video streaming apps",
                    "Dating apps",
                    "Other (specify):",
                    "None of the above"),
      rname = c("communication",
                "socialMedia",
                "audioStreaming",
                "videoStreaming",
                "dating",
                "other",
                "none"),
      reportingValues = c(1,2,3,4,5,6,7),
      writeIn = c(other = "character")) +

  # Burner Identity
  man(qname = "burnerIdentity",
      year = 2025,
      dname = "burnerIdentity",
      questionText = "Do you identify as a Burner?",
      questionType = "selectOne",
      responses = c("Yes",
                    "No",
                    "Sort of"),
      rname = c("yes",
                "no",
                "sortOf"),
      reportingValues = c(1,2,3)) +

  # Connected to Burner Community
  man(qname = "connectedToBurnerCommunity",
      year = 2025,
      dname = "connectedToBurnerCommunity",
      questionText = "How connected do you feel to the broader Burning Man community?",
      questionType = "selectOne",
      responses = c("Extremely connected",
                    "Very connected",
                    "Moderately connected",
                    "Slightly connected",
                    "Not at all connected"),
      rname = c("extremelyConnected",
                "veryConnected",
                "mdoeratelyConnected",
                "slightlyConnected",
                "notAtAllConnected"),
      reportingValues = c(1,2,3,4,5)) +

  # Involvement with regionals
  man(qname = "regionalInvolved",
      year = 2025,
      dname = "regionalInvolved",
      questionText = "In what ways have you been involved with a Regional Burning Man Event?",
      questionType = "selectMultiple",
      responses = c("Production (organization, preparation, coordination, etc.)",
                    "Staff/Volunteer (Ranger, Greeter, Gate, DPW, Resto, etc.)",
                    "Attending meetings",
                    "Medical services provider",
                    "Art project",
                    "Theme camp",
                    "Vendor",
                    "Performance",
                    "Donor",
                    "Supporter",
                    "Other (please specify):",
                    "I have not been involved with a Regional Burning Man event"),
      rname = c("production",
                "staffVolunteer",
                "meetings",
                "medical",
                "art",
                "themeCamp",
                "vendor",
                "performance",
                "donor",
                "supporter",
                "other",
                "notInvolved"),
      reportingValues = c(1,8,12,9,2,3,4,5,10,11,6,13),
      writeIn = c(other = "character")) +

  # Interest in becoming involved with the Burning Man community
  man(qname = "interestBurningManCommunity",
      year = 2025,
      dname = "interestBurningManCommunity",
      questionText = "How would you rate your interest in becoming more involved with the Burning Man community?",
      questionType = "selectOne",
      responses = c("Absolutely interested",
                    "Probably interested",
                    "Not sure",
                    "Probably not interested",
                    "Absolutely not interested"),
      rname = c("absolutelyInterested",
                "probablyInterested",
                "notSure",
                "Probably not interested",
                "Absolutely not interested"),
      reportingValues = c(1,2,3,4,5)) +

  # Inolvement in the Burning Man Community
  man(qname = "involvedBurningManCommunity",
      year = 2025,
      dname = "involvedBurningManCommunity",
      questionText = "In which way(s) would you like to be more involved? Check all that apply.",
      questionType = "selectMultiple",
      responses = c("By volunteering with a Burning Man Project department",
                    "By volunteering within my theme camp",
                    "By contributing to an art project",
                    "By volunteering with a Regional Burning Man group",
                    "In other ways (please specify):"),
      rname = c("volunteerWithBMPDepartment",
                "volunteerWithThemeCamp",
                "contributeToArt",
                "volunteerWithRegional",
                "other"),
      reportingValues = c(1,2,3,4,5),
      writeIn = c(other = "character")) +

  # Charitable donations
  man(qname = "charitableDonation",
      year = 2025,
      dname = "charitableDonation",
      questionText = "Have you made a charitable donation (of goods and/or money) toward any of the following in the last year?",
      questionType = "selectMultiple",
      responses = c("Burning Man Project",
                    "Regional Burning Man events and communities",
                    "Burners Without Borders",
                    "Fly Ranch Project",
                    "Art projects",
                    "Political campaigns or Voter registration",
                    "Schools or Universities",
                    "Animals or Environmental initiatives",
                    "Health-related initiatives",
                    "Human rights initiatives",
                    "Poverty-related initiatives",
                    "Religious or Faith-based initiatives",
                    "Community groups or Clubs",
                    "Self-initiated good deeds",
                    "Other nonprofits or charities (please specify):"),
      rname = c("burningManProject",
                "Regional",
                "burnersWithoutBorders",
                "flyRanch",
                "artPojects",
                "politicalCampaignsVoterRegistration",
                "schoolsUniversities",
                "animalsEnvironmentalInitiatives",
                "healthInitiatives",
                "humanRightsInitiatives",
                "povertyInitiatives",
                "religiousInitiatives",
                "communityGroupsClubs",
                "selfInitiatedGoodDeeds",
                "otherNonprofitsCharities"),
      reportingValues = c(1,2,3,11,4,5,6,7,12,13,15,14,8,9,10),
      writeIn = c(otherNonprofitsCharities = "character")) +

  # Importance of the 10 principles
  man(qname = "tenPrinciplesHowImportant",
      year = 2025,
      dname = "tenPrinciplesHowImportant",
      questionText = "How important are the 10 Principles to you?",
      questionType = "selectOne",
      responses = c("Very important",
                    "Important",
                    "Moderately important",
                    "Slightly important",
                    "Not important",
                    "I don't know"),
      rname = c("veryImportant",
                "important",
                "moderatelyImportant",
                "slightlyImportant",
                "notImportant",
                "dontKnow"),
      reportingValues = c(1,2,3,4,5,6)) +

  # Which of the 10 principles are the most important
  man(qname = "tenPrinciplesWhichImportant",
      year = 2025,
      dname = "tenPrinciplesWhichImportant",
      questionText = "Which of the 10 Principles are most important to you?",
      questionType = "selectMultiple",
      responses = c("Radical Inclusion: Anyone may be a part of Burning Man. We welcome and respect the stranger. No prerequisites exist for participation in our community.",
                    "Gifting: Burning Man is devoted to acts of gift giving. The value of a gift is unconditional. Gifting does not contemplate a return or an exchange for something of equal value.",
                    "Decommodification: In order to preserve the spirit of gifting, our community seeks to create social environments that are unmediated by commercial sponsorships, transactions, or advertising. We stand ready to protect our culture from such exploitation. We resist the substitution of consumption for participatory experience.",
                    "Radical Self-reliance: Burning Man encourages the individual to discover, exercise, and rely on their inner resources.",
                    "Radical Self-expression: Radical self-expression arises from the unique gifts of the individual. No one other than the individual or a collaborating group can determine its content. It is offered as a gift to others. In this spirit, the giver should respect the rights and liberties of the recipient.",
                    "Communal Effort: Our community values creative cooperation and collaboration. We strive to produce, promote and protect social networks, public spaces, works of art, and methods of communication that support such interaction.",
                    "Civic Responsibility: We value civil society. Community members who organize events should assume responsibility for public welfare and endeavor to communicate civic responsibilities to participants. They must also assume responsibility for conducting events in accordance with local, state, and federal laws.",
                    "Leaving No Trace: Our community respects the environment. We are committed to leaving no physical trace of our activities wherever we gather. We clean up after ourselves and endeavor, whenever possible, to leave such places in a better state than when we found them.",
                    "Participation: Our community is committed to a radically participatory ethic. We believe that transformative change, whether in the individual or in society, can occur only through the medium of deeply personal participation. We achieve being through doing. Everyone is invited to work. Everyone is invited to play. We make the world real through actions that open the heart.",
                    "Immediacy: Immediate experience is, in many ways, the most important touchstone of value in our culture. We seek to overcome barriers that stand between us and a recognition of our inner selves, the reality of those around us, participation in society, and contact with a natural world exceeding human powers. No idea can substitute for this experience."),
      rname = c("radicalInclusion",
                "gifting",
                "decommodification",
                "radicalSelfReliance",
                "radicalSelfExpression",
                "communalEffort",
                "civicResponsibility",
                "leaveNoTrace",
                "participation",
                "immediacy"),
      reportingValues = c("Radical Inclusion",
                          "Gifting",
                          "Decommodification",
                          "Radical Self-reliance",
                          "Radical Self-expression",
                          "Communal Effort",
                          "Civic Responsibility",
                          "Leaving No Trace",
                          "Participation",
                          "Immediacy"),
      notes.year = "Instructions say: check up to three") +

  # Incorporating 10 principles in daily life
  man(qname = "tenPrinciplesDailyLife",
      year = 2025,
      dname = "tenPrinciplesDailyLife",
      questionText = "Are you incorporating any of the 10 Principles in your daily life?",
      questionType = "selectOne",
      responses = c("Yes", "No", "Sort of"),
      rname = c("yes", "no", "sortOf"),
      reportingValues = c(5,6,7)) +

  # Arrival date
  man(qname = "arrivedDate",
      year = 2025,
      dname = "arrivedDate",
      questionText = "I arrived in Black Rock City the first time in 2025…",
      questionType = "selectOne",
      responses = c("Before Wed 8/20 (pre-event)",
                    "Wed 8/20 (pre-event)",
                    "Thu 8/21 (pre-event)",
                    "Fri 8/22 (pre-event)",
                    "Sat 8/23 (pre-event)",
                    "Sun 8/24",
                    "Mon 8/25",
                    "Tue 8/26",
                    "Wed 8/27",
                    "Thu 8/28",
                    "Fri 8/29",
                    "Sat 8/30",
                    "Sun 8/31",
                    "Mon 9/01 (post-event)",
                    "Tue 9/02 (post-event)",
                    "After Tuesday 9/02 (post-event)"),
      rname = c("preBeforeNeg4",
                "preNeg4",
                "preNeg3",
                "preNeg2",
                "preNeg1",
                "event0",
                "event1",
                "event2",
                "event3",
                "event4",
                "event5",
                "event6",
                "event7",
                "post8",
                "post9",
                "afterPost9"),
      reportingValues = c(1:16)) +

  # Leave date
  man(qname = "leaveDate",
      year = 2025,
      dname = "leaveDate",
      questionText = "I left Black Rock City (or plan to leave)…",
      questionType = "selectOne",
      responses = c("Before Sun 8/24 (pre-event)",
                    "Sun 8/24",
                    "Mon 8/25",
                    "Tue 8/26",
                    "Wed 8/27",
                    "Thu 8/28",
                    "Fri 8/29",
                    "Sat 8/30",
                    "Sun 8/31",
                    "Mon 9/01 (post-event)",
                    "Tue 9/02 (post-event)",
                    "Wed 9/03 (post-event)",
                    "Thu 9/04 (post-event)",
                    "After Thu 9/04 (post-event)"),
      rname = c("beforeEvent0",
                "event0",
                "event1",
                "event2",
                "event3",
                "event4",
                "event5",
                "event6",
                "event7",
                "post8",
                "post9",
                "post10",
                "post11",
                "postAfter11"),
      reportingValues = c(1:14)) +

  # Black Rock City Arrival Point
  man(qname = "arrivePoint",
      year = 2025,
      dname = "arrivePoint",
      questionText = "How did you arrive at Black Rock City? Select the best answer.",
      questionType = "selectOne",
      responses = c("Through the Gate in a vehicle (not a shuttle service)",
                    "Through the Gate in a Burner Express Bus",
                    "Through the Gate with another shuttle service",
                    "Through Point 1",
                    "Through Black Rock City airport (88NV)",
                    "Other (please specify)"),
      rname = c("gateInVehicle",
                "gateInBXB",
                "gateOtherShuttle",
                "point1",
                "airport",
                "other"),
      reportingValues = c(1,2,3,4,5,6),
      writeIn = c(other = "character")) +

  # Gerlach Stops
  man(qname = "gerlachStops",
      year = 2025,
      dname = "gerlachStops",
      questionText = "As you passed through the town of Gerlach on your way to or from Black Rock City, did you stop at/visit any of the following locations? Check all that apply.",
      questionType = "selectMultiple",
      responses = c("I did not pass through Gerlach",
                    "I did not stop in Gerlach",
                    "Burning Man Project office",
                    "Bruno's Country Club",
                    "Friends of Black Rock High Rock",
                    "Gas station",
                    "High Rock Pizza",
                    "Joe's Gerlach Club",
                    "Miners Club",
                    "Roadside vendors selling food",
                    "Roadside vendors selling non-food items (such as clothing, goggles, etc.)",
                    "Other (please specify):"),
      rname = c("didNotPassThrough",
                "didNotStop",
                "burningManProjectOffice",
                "brunosCountryClub",
                "friendsOfBlackRockHighRock",
                "gasStation",
                "highRockPizza",
                "joesGerlachClub",
                "minersClub",
                "roadsideFoodVendor",
                "roadsideNonfoodVendor",
                "other"),
      reportingValues = c(13,1:11),
      writeIn = c(other = "character")) +

  # Ride a bike in BRC
  man(qname = "rideBike",
      year = 2025,
      dname = "rideBike",
      questionText = "Did you ride a bike in Black Rock City?",
      questionType = "selectOne",
      responses = c("Yes, a regular bike",
                    "Yes, an e-bike",
                    "No",
                    "I don't know"),
      rname = c("yesRegularBike",
                "yesEbike",
                "no",
                "dontKnow"),
      reportingValues = c(1,4,2,3)) +

  # Money spent to travel to BRC
  man(qname = "spendTravelBRC",
      year = 2025,
      dname = "spendTravelBRC",
      questionText = "How much did you spend this year to travel to and from Black Rock City, including fuel, camp dues, food, lodging, airfare, supplies, etc. (but not including your ticket to the event)?",
      questionType = "textBoxNumeric") +

  # Money spent in Nevada
  man(qname = "spendNevada",
      year = 2025,
      dname = "spendNevada",
      questionText = "How much of this total amount was spent within the state of Nevada?",
      questionType = "textBoxNumeric") +

  #
  man(qname = "campAddressStreet",
      year = 2025,
      dname = "campAddressStreet",
      questionText = "Where was your (primary) campsite located?",
      questionType = "selectOne",
      responses = c("Esplanade",
                    "A street",
                    "B street",
                    "C street",
                    "D street",
                    "E street",
                    "F street",
                    "G street",
                    "H street",
                    "I street",
                    "J street",
                    "K street or beyond (e.g., walk-in camping, Depot)",
                    "Center Camp Plaza",
                    "DPW depot",
                    "Airport",
                    "I don't remember"),
      rname = c("esplanade",
                "A",
                "B",
                "C",
                "D",
                "E",
                "F",
                "G",
                "H",
                "I",
                "J",
                "K",
                "centerCampPlaza",
                "DPWDepot",
                "airport",
                "dontRemember"),
      reportingValues = c(13, 1:11, 15, 17, 19, 20)) +

  # Center camp radial address
  man(qname = "campCenterCampRadial",
      year = 2025,
      dname = "campCenterCampRadial",
      questionText = "centercamp",
      questionType = "selectOne",
      responses = c("Sector a",
                    "Sector b",
                    "Sector c",
                    "Sector d",
                    "Sector e",
                    "Sector f"),
      rname = c("a", "b", "c", "d", "e", "f"),
      reportingValues = c(1,2,3,4,5,6),
      notes.year = "Question appeared if 'Center Camp Plaza' was selected in previous question. Alchemer outputed question under the heading 'centercamp' instead of the question text. Actual question text is 'Where was your Center Camp Plaza campsite located?'") +

  # Camp street side
  man(qname = "campStreetSide",
      year = 2025,
      dname = "campStreetSide",
      questionText = "streetside",
      questionType = "selectOne",
      responses = c("On the side closer to Esplanade",
                    "On the side farther from Esplanade"),
      rname = c("closerToEsplanade",
                "fartherFromEsplanade"),
      reportingValues = c(1, 2),
      notes.year = "Question appeared if a letter street was selected in previous question. Alchemer outputed question under the heading 'streetside' instead of the question text. Actual question text is 'On which side of [selected letter street] was your campsite?'") +

  #
  man(qname = "campKStreetSide",
      year = 2025,
      dname = "campKStreetSide",
      questionText = "kstreetside",
      questionType = "selectOne",
      responses = c("On the side closer to Esplanade",
                    "On the side farther from Esplanade"),
      rname = c("closerToEsplanade",
                "fartherFromEsplanade"),
      reportingValues = c(1, 2),
      notes.year = "Question appeared if a K Street was selected in previous question. Alchemer outputed question under the heading 'kstreetside' instead of the question text. Actual question text is 'On which side of K street was your campsite?'") +

  #
  man(qname = "campAddressRadial",
      year = 2025,
      dname = "campAddressRadial",
      questionText = "radialblock",
      questionType = "selectOne",
      responses = c("Between 2:00 and 2:30",
                    "Between 2:30 and 3:00",
                    "Between 3:00 and 3:30",
                    "Between 3:30 and 4:00",
                    "Between 4:00 and 4:30",
                    "Between 4:30 and 5:00",
                    "Between 5:00 and 5:30",
                    "Between 5:30 and 6:00",
                    "Between 6:00 and 6:30",
                    "Between 6:30 and 7:00",
                    "Between 7:00 and 7:30",
                    "Between 7:30 and 8:00",
                    "Between 8:00 and 8:30",
                    "Between 8:30 and 9:00",
                    "Between 9:00 and 9:30",
                    "Between 9:30 and 10:00",
                    "10:00"),
      rname = c("between200and230",
                "between230and300",
                "between300and330",
                "between330and400",
                "between400and430",
                "between430and500",
                "between500and530",
                "between530and600",
                "between600and630",
                "between630and700",
                "between700and730",
                "between730and800",
                "between800and830",
                "between830and900",
                "between900and930",
                "between930and1000",
                "on1000"),
      reportingValues = c(1:17),
      notes.year = "Alchemer outputed question under the heading 'radialblock' instead of the question text. Actual question text is 'What was the radial address of your campsite?'") +

  # Camp Placed
  man(qname = "campPlaced",
      year = 2025,
      dname = "campPlaced",
      questionText = "Was your camp assigned a location by the Burning Man Placement Team before the event?",
      questionType = "selectOne",
      responses = c("Yes", "No", "I don't know"),
      rname = c("yes", "no", "dontKnow"),
      reportingValues = c(1, 2, 3)) +

  # Environmental impact
  man(qname = "reduceEnvironmentalImpact",
      year = 2025,
      dname = "reduceEnvironmentalImpact",
      questionText = "Which of the following actions were you motivated to take this year to reduce your environmental impact in Black Rock City? Check all that apply. ",
      questionType = "selectMultiple",
      responses = c("I am a member of a camp that creates sustainability-related content for other participants to experience",
                    "I used renewable energy (e.g., solar power) at my camp or project",
                    "I had a waste-reduction plan with my camp or crew",
                    "I minimized food waste by planning carefully, feeding others, or composting",
                    "I collected my greywater to be repurposed",
                    "I reduced or avoided single-use plastic for drinking water and other consumable items",
                    "I engaged in Leave No Trace and did more MOOP sweeps on playa",
                    "I actively helped others learn to reduce their environmental impact",
                    "I brought my aluminum cans to Recycle Camp",
                    "Other (please specify):",
                    "None of the above"),
      rname = c("memberOfSustainableCamp",
                "usedRenewableEnergy",
                "wasteReductionPlan",
                "minimizedFoodWaste",
                "collectedGreywater",
                "reducedPlastic",
                "leaveNoTrace",
                "helpedOthersLearn",
                "cansToRecycleCamp",
                "other",
                "none"),
      reportingValues = c(1,2,3,4,5,6,7,8,9,10,11),
      writeIn = c(other = "character")) +

  # Create Diversity
  man(qname = "createDiversity",
      year = 2025,
      dname = "createDiversity",
      questionText = "How did you (and/or your camp or project) help create a more welcoming and diverse Black Rock City this year? We're especially interested in actions that support inclusion across age, nationality, politics, sexual orientation, race, and more.",
      questionType = "selectMultiple",
      responses = c("The camp or project(s) I am involved in welcomed new participants who are members of under-represented groups in BRC",
                    "My camp or project offers financial assistance to low-income Burners or other under-represented groups",
                    "Other (please specify):",
                    "None of the above"),
      rname = c("welcomedUnderRepresentedGroups",
                "financialAssistance",
                "other",
                "none"),
      reportingValues = c(1,2,3,4),
      writeIn = c(other = "character")) +

  # Challenges to attending Burning Man
  man(qname = "attendChallenge",
      year = 2025,
      dname = "attendChallenge",
      questionText = "What was your biggest challenge in planning to attend this year?",
      questionType = "selectOne",
      responses = c("Getting a ticket",
                    "Cost of attendance",
                    "Finding transportation",
                    "Getting time off work/school",
                    "Finding people to attend with",
                    "Learning what to bring/how to prepare",
                    "Other (please specify):",
                    "There was no challenge involved in the planning"),
      rname = c("ticket",
                "cost",
                "transportation",
                "timeOff",
                "findingPeople",
                "learning",
                "other",
                "noChallenge"),
      reportingValues = c(1,2,3,4,5,6,7,8),
      writeIn = c(other = "character")) +

  # Attend Burning Many Next Year
  man(qname = "attendNextYear",
      year = 2025,
      dname = "attendNextYear",
      questionText = "Do you plan to come back to Black Rock City next year?",
      questionType = "selectOne",
      responses = c("Absolutely",
                    "Probably",
                    "Not sure",
                    "Probably not",
                    "Absolutely not"),
      rname = c("absolutely",
                "probably",
                "notSure",
                "probablyNot",
                "Absolutely not"),
      reportingValues = c(1,2,3,4,5)) +

  # Come back to BRC in the future
  man(qname = "attendTwoOrMoreYears",
      year = 2025,
      dname = "attendTwoOrMoreYears",
      questionText = "Do you plan to come back to Black Rock City in 2027 or further in the future?",
      questionType = "selectOne",
      responses = c("Absolutely",
                    "Probably",
                    "Not sure",
                    "Probably not",
                    "Absolutely not"),
      rname = c("absolutely",
                "probably",
                "notSure",
                "probablyNot",
                "absolutelyNot"),
      reportingValues = c(1,2,3,4,5)) +

  # Reason to Return to BRC
  man(qname = "reasonToReturnToBRC",
      year = 2025,
      dname = "reasonToReturnToBRC",
      questionText = "Which of the following reasons indicate why you might return to Black Rock City in the future? Check all that apply.",
      questionType = "selectMultiple",
      responses = c("To volunteer with a theme camp or Burning Man Project department",
                    "To see and experience the art",
                    "To create or work on a project",
                    "To be with friends or like-minded people or feel a sense of belonging",
                    "To meet people who are different from me",
                    "To play and experience freedom",
                    "To consume intoxicants",
                    "To escape the world for a time",
                    "To express myself",
                    "To experience gifting and decommodification",
                    "To rely on myself and practice useful skills",
                    "To perform and practice artistic skills",
                    "To satisfy my curiosity or check it off my 'bucket list'",
                    "To grow or connect spiritually",
                    "To satisfy someone else's wish that I be there",
                    "Other (please specify):"),
      rname = c("volunteer",
                "seeExperienceArt",
                "createWorkOnProject",
                "likeMindedPeopleBelonging",
                "meetPeopleDifferentFromMe",
                "playExperienceFreedom",
                "consumeIntoxicants",
                "escapeWorld",
                "expressMyself",
                "giftingDecommodication",
                "relyOnMyselfPracticeSkills",
                "performPracticeArtSkills",
                "curiosityBucketList",
                "growConnectSpiritually",
                "satisfySomeoneElse",
                "other"),
      reportingValues = c(1:16),
      writeIn = c(other = "character")) +

  # How did you hear about Census
  man(qname = "hearAboutCensus",
      year = 2025,
      dname = "hearAboutCensus",
      questionText = "How did you hear about the BRC Census online survey (the form you are currently filling out)?",
      questionType = "selectMultiple",
      responses = c("Email including a link",
                    "Word of mouth (e.g. friends, campmates, etc.)",
                    "I have known about it for multiple years and always try to fill it out",
                    "I saw a Census sign during exodus",
                    "I was randomly sampled at Gate, Airport, or on a Burner Express Bus",
                    "I filled out a Field Notes book and saw the reminder in the book",
                    "I heard about it on BMIR",
                    "Through my Burner Profile",
                    "I was gifted a Census sticker",
                    "I saw a post about it on the Burning Man Journal",
                    "I saw a reminder on the Jackrabbit Speaks",
                    "I received an email about it from a volunteer department, theme camp, etc.",
                    "I saw a Census sign in a theme camp",
                    "ePlaya, Facebook, Reddit, Instagram, and/or other social networks",
                    "I found a link to the survey in the header of the burningman.org website",
                    "SF Decompression or another regional Burning Man event",
                    "Other - Please specify:"),
      rname = c("emailWithLink",
                "wordOfMouth",
                "knownForYears",
                "censusSignExodus",
                "randomSample",
                "fieldNotes",
                "BMIR",
                "burnerProfile",
                "censusSticker",
                "burningManJournal",
                "jackrabbitSpeaks",
                "emailDepartmentCamp",
                "censusSignCamp",
                "socialNetwork",
                "burningManWebsite",
                "decompression",
                "other"),
      reportingValues = c(15,1,2,3,4,5,6,16,7,8,9,10,11,12,17,13,14),
      writeIn = c(other = "character")) +

  # Seen the results of the BRC Census
  man(qname = "seenCensusResults",
      year = 2025,
      dname = "seenCensusResults",
      questionText = "Have you ever seen the results of the Black Rock City Census from this year or past years? Check all that apply.",
      questionType = "selectMultiple",
      responses = c("Yes, I read a Black Rock City Census report (blackrockcitycensus.org) in the past",
                    "Yes, I saw Census results elsewhere (e.g., Burning Man Journal, Census Lab on playa)",
                    "No, I've never seen Black Rock City Census results"),
      rname = c("yesReadReport",
                "yesElsewhere",
                "no"),
      reportingValues = c(1,2,3)) +

  # Data Nerds
  man(qname = "dataNerds",
      year = 2025,
      dname = "dataNerds",
      questionText = "Now that you have completed the core section of the Black Rock City Census, are you willing to answer up to 16 more questions to support academic researchers studying different aspects of the Burning Man experience?",
      questionType = "selectOne",
      responses = c("Yes", "No"),
      rname = c("yes", "no"),
      reportingValues = c(1, 2)) +

  # Use a playa name
  man(qname = "playaNameUse",
      year = 2025,
      dname = "playaNameUse",
      questionText = "Did you use a playa name this year at Burning Man?",
      questionType = "selectOne",
      responses = c("Yes", "No"),
      rname = c("yes", "no"),
      reportingValues = c(1,2)) +

  # Acqure a playa name
  man(qname = "playaNameAcquire",
      year = 2025,
      dname = "playaNameAcquire",
      questionText = "How did you acquire this playa name?",
      questionType = "selectOne",
      responses = c("I chose it myself",
                    "It was given to me by a Burning Man participant",
                    "It was given to me by someone outside the Burning Man community",
                    "Other (please specify):"),
      rname = c("choseItMyself",
                "givenToMeParticipant",
                "givenToMeOutside",
                "other"),
      reportingValues = c(1,2,3,4),
      writeIn = c(other = "character")) +

  # Years playa name has been used
  man(qname = "playaNameYears",
      year = 2025,
      dname = "playaNameYears",
      questionText = "How many years have you been using this playa name?",
      questionType = "selectOne",
      responses = c("I started using this playa name this year",
                    "I have used this playa name for multiple years (please specify the number of years):"),
      rname = c("startedThisYear", "usedMultipleYears"),
      reportingValues = c(1, 2),
      writeIn = c(usedMultipleYears = "numeric")) +

  #
  man(qname = "playaNameEffect",
      year = 2025,
      dname = "playaNameEffect",
      questionText = "To what extend did your playa name...",
      questionType = "selectScale",
      responses = c("Reflect your identity in the default world",
                    "Reflect an identity that you do not usually express in the default world",
                    "Reflect who you would like to be in your daily life",
                    "Enhance the way others perceive you or connect with you",
                    "Help you feel free of stigma or marginalization due to your default world identity",
                    "Help you be more engaged or present at Burning Man",
                    "Help you maintain your privacy or anonymity at Burning Man",
                    "Help you feel more comfortable or less shy communicating with others at Burning Man"),
      rname = c("reflectDefaultIdentity",
                "reflectUnusualIdentity",
                "reflectDailyLife",
                "enchanceOthersPerception",
                "freeOfStigma",
                "beMoreEngagedPresent",
                "maintainPrivacy",
                "feelComfortableCommunicating"),
      scaleOptions = c("Not at all",
                       "Slightly",
                       "Moderately",
                       "Very much",
                       "Extremely"),
      reportingValues = c(1,2,3,4,5)) +

  # Contribution to making art
  man(qname = "artMakingContribute",
      year = 2025,
      dname = "artMakingContribute",
      questionText = "Did you contribute to artmaking for Burning Man this year? Artmaking is defined as anything you participate in that generates performative, digital, or material objects for creative expression. Check all that apply.",
      questionType = "selectMultiple",
      responses = c("Yes, I contributed to making artistic material objects (e.g., sculpture, painting, jewelry, clothing)",
                    "Yes, I contributed to making digital art (e.g., photography, videos, recorded music)",
                    "Yes, I contributed to performative art (e.g., dance, fire spinning, musical instrument, skit)",
                    "Yes, I contributed to another art form (please specify):",
                    "No, I did not contribute to artmaking"),
      rname = c("yesContributedMaterial",
                "yesContributedDigital",
                "yesContributedPerformative",
                "yesContributedOtherArt",
                "no"),
      reportingValues = c(1,2,5,6,7),
      writeIn = c(yesContributedOtherArt = "character")) +

  # Importance of making art
  man(qname = "artMakingImportance",
      year = 2025,
      dname = "artMakingImportance",
      questionText = "How important was artmaking (your own or other people's artmaking) to your experience at Burning Man?",
      questionType = "selectOne",
      responses = c("Most important, it was my primary purpose for attending Burning Man this year",
                    "Very important",
                    "Important",
                    "Somewhat important",
                    "Not important"),
      rname = c("mostImportant",
                "veryImportant",
                "important",
                "somewhatImportant",
                "notImportant"),
      reportingValues = c(1,2,3,4,5)) +

  # Art Making Avenue
  man(qname = "artMakingAvenue",
      year = 2025,
      dname = "artMakingAvenue",
      questionText = "Is Burning Man your primary artmaking avenue?",
      questionType = "selectOne",
      responses = c("Yes", "No", "I have no artmaking avenue"),
      rname = c("yes", "no", "noAvenue"),
      reportingValues = c(1,2,3)) +

  # Make art with friends
  man(qname = "artMakingFriends",
      year = 2025,
      dname = "artMakingFriends",
      questionText = "Did you make new friends by participating in artmaking for/at Burning Man this year?",
      questionType = "selectOne",
      responses = c("Yes", "No"),
      rname = c("yes", "no"),
      reportingValues = c(1, 2)) +

  # Collaborate on making art
  man(qname = "artMakingCollaborate",
      year = 2025,
      dname = "artMakingCollaborate",
      questionText = "Do you collaborate with people from the Burning Man community on artmaking that is unrelated to Burning Man?",
      questionType = "selectOne",
      responses = c("Yes", "No"),
      rname = c("yes", "no"),
      reportingValues = c(1, 2))

jsonlite::write_json(man2025, path = "man2025.json")
