library(shiny)
library(shinyjs)

# ── helpers ──────────────────────────────────────────────────────────────────

`%||%` <- function(a, b) if (!is.null(a) && length(a) > 0 && a != "") a else b

is_alchemy <- function(year) {
  yr <- suppressWarnings(as.integer(year))
  !is.na(yr) && yr >= 2022
}

to_rname <- function(x) {
  x <- trimws(x)
  x <- gsub("[^A-Za-z0-9 ]", "", x)
  x <- gsub("\\s+(.)", "\\U\\1", x, perl = TRUE)
  x <- gsub("\\s", "", x)
  if (nchar(x) == 0) return("item")
  if (grepl("^[0-9]", x)) x <- paste0("x", x)
  x
}

r_str      <- function(x) paste0('"', gsub('"', '\\"', x), '"')
r_char_vec <- function(v) {
  v <- v[nchar(trimws(v)) > 0]
  if (length(v) == 0) return(NULL)
  if (length(v) == 1) return(r_str(v))
  paste0("c(", paste(sapply(v, r_str), collapse = ",\n           "), ")")
}
r_num_vec  <- function(v) {
  v <- v[nchar(trimws(v)) > 0]
  if (length(v) == 0) return(NULL)
  if (length(v) == 1) return(trimws(v))
  paste0("c(", paste(trimws(v), collapse = ", "), ")")
}

# Parse bulk paste text → list of list(label, value, rname)
parse_bulk <- function(txt) {
  lines <- strsplit(txt, "\n")[[1]]
  lines <- trimws(lines)
  lines <- lines[nchar(lines) > 0]
  lapply(lines, function(ln) {
    parts <- strsplit(ln, "\\|")[[1]]
    parts <- trimws(parts)
    list(
      label = parts[1] %||% "",
      value = if (length(parts) >= 2) parts[2] else "",
      rname = if (length(parts) >= 3) parts[3] else ""
    )
  })
}

build_man_call <- function(d) {
  lines <- c(
    paste0('man(qname         = ', r_str(d$qname), ','),
    paste0('    year          = ', d$year, ',')
  )
  if (nchar(trimws(d$dname %||% "")) > 0)
    lines <- c(lines, paste0('    dname         = ', r_str(d$dname), ','))
  lines <- c(lines,
    paste0('    questionText  = ', r_str(d$questionText), ','),
    paste0('    questionType  = ', r_str(d$questionType), ',')
  )

  qt <- d$questionType

  if (qt %in% c("selectOne", "selectMultiple")) {
    resp_labels <- d$resp_labels
    resp_values <- d$resp_values
    wi_labels   <- d$wi_labels
    wi_types    <- d$wi_types
    rnames      <- d$rnames

    if (!is.null(resp_labels) && length(resp_labels) > 0) {
      lines <- c(lines, paste0('    responses     = ', r_char_vec(resp_labels), ','))
      if (!is.null(rnames) && length(rnames) > 0)
        lines <- c(lines, paste0('    rname         = ', r_char_vec(rnames), ','))
      if (is_alchemy(d$year) && !is.null(resp_values) && length(resp_values) > 0 && any(nchar(trimws(resp_values)) > 0))
        lines <- c(lines, paste0('    reportingValues = ', r_num_vec(resp_values), ','))
    }
    if (!is.null(wi_labels) && length(wi_labels) > 0) {
      lines <- c(lines, paste0('    writeInResponses = ', r_char_vec(wi_labels), ','))
      wt <- wi_types[nchar(trimws(wi_types)) > 0]
      if (length(wt) > 0) {
        if (length(wt) == 1)
          lines <- c(lines, paste0('    writeInTypes  = ', r_str(wt), ','))
        else
          lines <- c(lines, paste0('    writeInTypes  = ', r_char_vec(wt), ','))
      }
      if (nchar(trimws(d$wname %||% "")) > 0)
        lines <- c(lines, paste0('    wname         = ', r_str(d$wname), ','))
    }

  } else if (qt == "selectScale") {
    row_labels <- d$scale_row_labels
    scale_opts <- d$scale_opts
    rnames     <- d$rnames
    scale_vals <- d$scale_vals

    if (!is.null(row_labels) && length(row_labels) > 0) {
      lines <- c(lines, paste0('    responses     = ', r_char_vec(row_labels), ','))
      if (!is.null(rnames) && length(rnames) > 0)
        lines <- c(lines, paste0('    rname         = ', r_char_vec(rnames), ','))
    }
    if (!is.null(scale_opts) && length(scale_opts) > 0) {
      lines <- c(lines, paste0('    scaleOptions  = ', r_char_vec(scale_opts), ','))
      if (is_alchemy(d$year) && !is.null(scale_vals) && length(scale_vals) > 0 && any(nchar(trimws(scale_vals)) > 0))
        lines <- c(lines, paste0('    reportingValues = ', r_num_vec(scale_vals), ','))
    }

  } else if (qt %in% c("textBoxNumeric", "textBoxCharacter")) {
    if (nchar(trimws(d$text_pattern %||% "")) > 0)
      lines <- c(lines, paste0('    responses     = ', r_str(d$text_pattern), ','))
  }

  if (nchar(trimws(d$notes_qname %||% "")) > 0)
    lines <- c(lines, paste0('    notes.qname   = ', r_str(d$notes_qname), ','))
  if (nchar(trimws(d$notes_year %||% "")) > 0)
    lines <- c(lines, paste0('    notes.year    = ', r_str(d$notes_year), ','))

  last <- length(lines)
  lines[last] <- sub(",$", "", lines[last])
  lines <- c(lines, ")")
  paste(lines, collapse = "\n")
}

generate_r_file <- function(records) {
  header <- paste0(
    "# BRC Census man() records\n",
    "# Generated by burnr_form Shiny app on ", Sys.Date(), "\n",
    "library(burnr)\n\n"
  )
  calls <- sapply(records, build_man_call)
  paste0(header, paste(calls, collapse = "\n\n"))
}

# ── UI ───────────────────────────────────────────────────────────────────────

ui <- fluidPage(
  useShinyjs(),
  tags$head(tags$style(HTML("
    body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 14px; }
    .param-badge {
      font-family: monospace; font-size: 10px;
      background: #e8f0fe; color: #1a56db;
      border-radius: 3px; padding: 1px 4px; margin-left: 4px;
      vertical-align: middle;
    }
    .platform-badge {
      font-size: 11px; font-weight: bold;
      border-radius: 4px; padding: 2px 8px; margin-left: 8px;
    }
    .badge-alchemy  { background: #fde68a; color: #92400e; }
    .badge-surveygizmo { background: #d1fae5; color: #065f46; }
    .badge-unknown  { background: #f3f4f6; color: #6b7280; }
    .section-header {
      background: #f3f4f6; border-left: 4px solid #1a56db;
      padding: 6px 12px; margin: 12px 0 8px 0;
      font-weight: bold; font-size: 13px;
    }
    .resp-row { margin-bottom: 4px; }
    .preview-box {
      background: #1e1e1e; color: #d4d4d4;
      font-family: monospace; font-size: 12px;
      padding: 12px; border-radius: 6px;
      white-space: pre; overflow-x: auto;
      min-height: 120px;
    }
    .record-card {
      border: 1px solid #d1d5db; border-radius: 6px;
      padding: 8px 12px; margin-bottom: 6px; background: #fff;
    }
    .record-card:hover { border-color: #1a56db; background: #f0f4ff; }
    .hint { font-size: 11px; color: #6b7280; margin-top: 2px; margin-bottom: 6px; }
    .col-header { font-size: 11px; color: #6b7280; font-weight: bold; padding: 2px 4px; }
    .bulk-area { background: #f9fafb; border: 1px dashed #d1d5db;
                 border-radius: 6px; padding: 10px; margin-top: 8px; }
    hr { border-top: 1px solid #e5e7eb; margin: 12px 0; }
  "))),

  titlePanel("BRC Census — burnr Question Record Builder"),

  fluidRow(
    # ── LEFT: form ──────────────────────────────────────────────────────────
    column(5,
      wellPanel(
        div(class = "section-header", "Question Identity"),

        fluidRow(
          column(6,
            tags$label(HTML('Short name / question ID <span class="param-badge">qname</span>')),
            textInput("qname", NULL, placeholder = "e.g. attendanceYear or Q12"),
            div(class = "hint",
                "camelCase R name (e.g. attendanceYear) — or a question ID from the survey ",
                "(e.g. AQID, Q12) if the R name is not yet known. Murrs can standardize later.")
          ),
          column(6,
            tags$label(HTML(
              'Survey year <span class="param-badge">year</span>'
            ), uiOutput("platform_badge", inline = TRUE)),
            numericInput("year", NULL, value = 2025, min = 1990, max = 2100, step = 1)
          )
        ),

        tags$label(HTML('Dataset column name <span class="param-badge">dname</span>')),
        textInput("dname", NULL, placeholder = "leave blank if unknown"),
        div(class = "hint",
            "The variable name used in the data file. ",
            "For Alchemy years (2022+) this is Hunter's column name. ",
            "For SurveyGizmo years it may be a field ID. Leave blank if unsure."),

        tags$label(HTML('Full question text <span class="param-badge">questionText</span>')),
        textAreaInput("questionText", NULL, rows = 3,
                      placeholder = "Paste the exact question wording from the survey PDF"),

        tags$label(HTML('Question type <span class="param-badge">questionType</span>')),
        selectInput("questionType", NULL,
                    choices = c(
                      "Select one (radio / dropdown menu)" = "selectOne",
                      "Select multiple (checkboxes)"       = "selectMultiple",
                      "Rating scale grid"                  = "selectScale",
                      "Numeric text box"                   = "textBoxNumeric",
                      "Text / open-ended"                  = "textBoxCharacter",
                      "Rank order"                         = "rank"
                    )),
        div(class = "hint",
            "'Select one' covers both radio buttons AND dropdown menus (e.g. year of birth)."),

        # ── text box pattern ────────────────────────────────────────────────
        conditionalPanel(
          condition = "input.questionType == 'textBoxNumeric' || input.questionType == 'textBoxCharacter'",
          tags$label(HTML('Validation pattern (optional) <span class="param-badge">responses</span>')),
          textInput("text_pattern", NULL, placeholder = "e.g. [0-9]{5} for ZIP code"),
          div(class = "hint", "A regex pattern if the question enforces a specific format.")
        ),

        # ── response rows ───────────────────────────────────────────────────
        conditionalPanel(
          condition = "input.questionType == 'selectOne' || input.questionType == 'selectMultiple' || input.questionType == 'selectScale'",

          div(class = "section-header",
            conditionalPanel(condition = "input.questionType == 'selectScale'",
              HTML('Grid rows — items being rated <span class="param-badge">responses / rname</span>')
            ),
            conditionalPanel(
              condition = "input.questionType != 'selectScale'",
              HTML('Response options <span class="param-badge">responses / rname / reportingValues</span>')
            )
          ),

          uiOutput("response_col_headers"),
          div(id = "response_rows"),

          fluidRow(
            column(5, actionButton("add_response", "+ Add row",
                                   class = "btn-sm btn-default", style = "margin-top:4px;")),
            column(7, actionButton("toggle_bulk_resp", "Paste / bulk import ▾",
                                   class = "btn-sm btn-link", style = "margin-top:4px;"))
          ),

          # Bulk paste panel
          shinyjs::hidden(
            div(id = "bulk_resp_panel", class = "bulk-area",
              tags$p(style = "font-size:12px; margin-bottom:6px;",
                "One option per line. Separate fields with  |  (pipe):",
                tags$br(),
                tags$code("Option label"),
                tags$br(),
                tags$code("Option label | numeric value"),
                tags$br(),
                tags$code("Option label | numeric value | rname")
              ),
              textAreaInput("bulk_resp_text", NULL, rows = 6,
                            placeholder = "1964\n1965\n1966\n...\n\nor:\nMale | 1\nFemale | 2\nNon-binary | 3"),
              actionButton("bulk_resp_import", "Import rows", class = "btn-sm btn-primary")
            )
          )
        ),

        # ── selectScale: scale columns ──────────────────────────────────────
        conditionalPanel(
          condition = "input.questionType == 'selectScale'",
          div(class = "section-header",
            HTML('Scale column labels <span class="param-badge">scaleOptions / reportingValues</span>')
          ),
          uiOutput("scale_col_headers"),
          div(id = "scale_rows"),

          fluidRow(
            column(5, actionButton("add_scale", "+ Add scale option",
                                   class = "btn-sm btn-default", style = "margin-top:4px;")),
            column(7, actionButton("toggle_bulk_scale", "Paste / bulk import ▾",
                                   class = "btn-sm btn-link", style = "margin-top:4px;"))
          ),
          shinyjs::hidden(
            div(id = "bulk_scale_panel", class = "bulk-area",
              tags$p(style = "font-size:12px; margin-bottom:6px;",
                "One scale option per line:",
                tags$br(),
                tags$code("Never"),
                tags$br(),
                tags$code("Never | 1")
              ),
              textAreaInput("bulk_scale_text", NULL, rows = 4,
                            placeholder = "Never\nRarely\nSometimes\nOften\nAlways"),
              actionButton("bulk_scale_import", "Import rows", class = "btn-sm btn-primary")
            )
          )
        ),

        # ── write-in section ────────────────────────────────────────────────
        conditionalPanel(
          condition = "input.questionType == 'selectOne' || input.questionType == 'selectMultiple'",
          div(class = "section-header",
            HTML('Write-in responses (optional) <span class="param-badge">writeInResponses / writeInTypes / wname</span>')
          ),
          div(class = "hint",
              "Only fill this in if the question has an \"Other — please specify\" or similar free-text option. ",
              "Leave empty if there is no write-in."),
          fluidRow(
            column(4, div(class = "col-header", "Write-in label")),
            column(3, div(class = "col-header", "Type")),
            column(3, div(class = "col-header", HTML("wname <span class='param-badge'>optional</span>")))
          ),
          div(id = "writein_rows"),
          actionButton("add_writein", "+ Add write-in", class = "btn-sm btn-default",
                       style = "margin-top:4px;")
        ),

        hr(),

        div(class = "section-header", "Notes"),
        fluidRow(
          column(6,
            tags$label(HTML('Variable note <span class="param-badge">notes.qname</span>')),
            textAreaInput("notes_qname", NULL, rows = 2,
                          placeholder = "Notes about this question (wording changes, oddities, etc.)")
          ),
          column(6,
            tags$label(HTML('Year note <span class="param-badge">notes.year</span>')),
            textAreaInput("notes_year", NULL, rows = 2,
                          placeholder = "Notes specific to this survey year")
          )
        ),

        hr(),

        fluidRow(
          column(6, actionButton("save_record", "Save record",
                                 class = "btn-primary btn-sm", style = "width:100%")),
          column(6, actionButton("clear_form",  "Clear form",
                                 class = "btn-default btn-sm", style = "width:100%"))
        ),
        div(class = "hint", style = "text-align:center; margin-top:6px;",
            "Year is kept between saves so you can enter a full survey without resetting it.")
      )
    ),

    # ── RIGHT: preview + record list ────────────────────────────────────────
    column(7,
      div(class = "section-header", "Live R preview"),
      div(class = "preview-box", verbatimTextOutput("preview", placeholder = TRUE)),

      hr(),

      div(class = "section-header",
        "Saved records",
        downloadButton("download_r", "Download .R file",
                       class = "btn-xs btn-success", style = "float:right; margin-top:-4px;")
      ),
      uiOutput("record_list")
    )
  )
)

# ── Server ───────────────────────────────────────────────────────────────────

server <- function(input, output, session) {

  rv <- reactiveValues(
    records             = list(),
    resp_row_ids        = character(0),
    scale_row_ids       = character(0),
    writein_row_ids     = character(0),
    editing_idx         = NULL,
    suppress_type_change = FALSE
  )

  # ── Platform badge ─────────────────────────────────────────────────────────
  output$platform_badge <- renderUI({
    req(input$year)
    yr <- suppressWarnings(as.integer(input$year))
    if (is.na(yr)) return(NULL)
    if (yr >= 2022)
      tags$span(class = "platform-badge badge-alchemy",    "Alchemy (2022+)")
    else if (yr >= 2012)
      tags$span(class = "platform-badge badge-surveygizmo","SurveyGizmo era")
    else
      tags$span(class = "platform-badge badge-unknown",    as.character(yr))
  })

  # ── Column headers (vary by type & year) ───────────────────────────────────
  output$response_col_headers <- renderUI({
    qt      <- input$questionType %||% "selectOne"
    alchemy <- is_alchemy(input$year %||% 0)
    if (qt == "selectScale") {
      fluidRow(
        column(7, div(class = "col-header", "Item label (row)")),
        column(4, div(class = "col-header", HTML("R name <span class='param-badge'>rname</span>")))
      )
    } else if (alchemy) {
      fluidRow(
        column(5, div(class = "col-header", "Response label")),
        column(3, div(class = "col-header", HTML("R name <span class='param-badge'>rname</span>"))),
        column(2, div(class = "col-header", HTML("Value <span class='param-badge'>reportingValues</span>"))),
        column(1)
      )
    } else {
      fluidRow(
        column(6, div(class = "col-header", "Response label")),
        column(4, div(class = "col-header", HTML("R name <span class='param-badge'>rname</span>"))),
        column(1)
      )
    }
  })

  output$scale_col_headers <- renderUI({
    alchemy <- is_alchemy(input$year %||% 0)
    if (alchemy) {
      fluidRow(
        column(6, div(class = "col-header", "Scale label")),
        column(3, div(class = "col-header", HTML("Value <span class='param-badge'>reportingValues</span>"))),
        column(1)
      )
    } else {
      fluidRow(
        column(9, div(class = "col-header", "Scale label")),
        column(1)
      )
    }
  })

  # ── Row factory ────────────────────────────────────────────────────────────
  next_id <- local({ n <- 0L; function() { n <<- n + 1L; as.character(n) } })

  make_response_row <- function(rid, label = "", rname = "", value = "") {
    qt      <- isolate(input$questionType) %||% "selectOne"
    alchemy <- is_alchemy(isolate(input$year) %||% 0)
    del_btn <- tags$button(class = "btn btn-xs btn-danger",
      onclick = sprintf("Shiny.setInputValue('delete_resp_row','%s',{priority:'event'})", rid), "×")
    if (qt == "selectScale") {
      div(class = "resp-row", id = paste0("resp_row_", rid),
        fluidRow(
          column(7, textInput(paste0("resp_label_", rid), NULL, value = label, placeholder = "Item being rated")),
          column(4, textInput(paste0("resp_rname_", rid), NULL, value = rname, placeholder = "auto")),
          column(1, del_btn)
        ))
    } else if (alchemy) {
      div(class = "resp-row", id = paste0("resp_row_", rid),
        fluidRow(
          column(5, textInput(paste0("resp_label_", rid), NULL, value = label, placeholder = "Response text")),
          column(3, textInput(paste0("resp_rname_", rid), NULL, value = rname, placeholder = "auto")),
          column(2, textInput(paste0("resp_value_", rid), NULL, value = value, placeholder = "int")),
          column(1, del_btn)
        ))
    } else {
      div(class = "resp-row", id = paste0("resp_row_", rid),
        fluidRow(
          column(6, textInput(paste0("resp_label_", rid), NULL, value = label, placeholder = "Response text")),
          column(4, textInput(paste0("resp_rname_", rid), NULL, value = rname, placeholder = "auto")),
          column(1, del_btn)
        ))
    }
  }

  make_scale_row <- function(rid, label = "", value = "") {
    alchemy <- is_alchemy(isolate(input$year) %||% 0)
    del_btn <- tags$button(class = "btn btn-xs btn-danger",
      onclick = sprintf("Shiny.setInputValue('delete_scale_row','%s',{priority:'event'})", rid), "×")
    if (alchemy) {
      div(class = "resp-row", id = paste0("scale_row_", rid),
        fluidRow(
          column(6, textInput(paste0("scale_label_", rid), NULL, value = label, placeholder = "e.g. Never")),
          column(3, textInput(paste0("scale_value_", rid), NULL, value = value, placeholder = "int")),
          column(1, del_btn)
        ))
    } else {
      div(class = "resp-row", id = paste0("scale_row_", rid),
        fluidRow(
          column(9, textInput(paste0("scale_label_", rid), NULL, value = label, placeholder = "e.g. Never")),
          column(1, del_btn)
        ))
    }
  }

  make_writein_row <- function(rid, label = "", type = "character", wname = "") {
    del_btn <- tags$button(class = "btn btn-xs btn-danger",
      onclick = sprintf("Shiny.setInputValue('delete_writein_row','%s',{priority:'event'})", rid), "×")
    div(class = "resp-row", id = paste0("writein_row_", rid),
      fluidRow(
        column(4, textInput(paste0("wi_label_", rid), NULL, value = label, placeholder = "e.g. Other (specify):")),
        column(3, selectInput(paste0("wi_type_",  rid), NULL, choices = c("character","numeric"), selected = type)),
        column(3, textInput(paste0("wi_wname_", rid), NULL, value = wname, placeholder = "e.g. otherText")),
        column(1, del_btn)
      ))
  }

  # ── Bulk paste toggles ─────────────────────────────────────────────────────
  observeEvent(input$toggle_bulk_resp,  shinyjs::toggle("bulk_resp_panel"))
  observeEvent(input$toggle_bulk_scale, shinyjs::toggle("bulk_scale_panel"))

  # ── Bulk import — responses ────────────────────────────────────────────────
  observeEvent(input$bulk_resp_import, {
    txt <- trimws(input$bulk_resp_text %||% "")
    if (nchar(txt) == 0) return()
    rows <- parse_bulk(txt)
    for (row in rows) {
      rid <- next_id()
      insertUI(selector = "#response_rows", where = "beforeEnd",
               ui = make_response_row(rid, row$label, row$rname, row$value), immediate = TRUE)
      rv$resp_row_ids <- c(rv$resp_row_ids, rid)
    }
    updateTextAreaInput(session, "bulk_resp_text", value = "")
    shinyjs::hide("bulk_resp_panel")
  })

  # ── Bulk import — scale ────────────────────────────────────────────────────
  observeEvent(input$bulk_scale_import, {
    txt <- trimws(input$bulk_scale_text %||% "")
    if (nchar(txt) == 0) return()
    rows <- parse_bulk(txt)
    for (row in rows) {
      rid <- next_id()
      insertUI(selector = "#scale_rows", where = "beforeEnd",
               ui = make_scale_row(rid, row$label, row$value), immediate = TRUE)
      rv$scale_row_ids <- c(rv$scale_row_ids, rid)
    }
    updateTextAreaInput(session, "bulk_scale_text", value = "")
    shinyjs::hide("bulk_scale_panel")
  })

  # ── Clear rows helper ──────────────────────────────────────────────────────
  clear_rows <- function() {
    for (rid in rv$resp_row_ids)    removeUI(paste0("#resp_row_",    rid), immediate = TRUE)
    for (rid in rv$scale_row_ids)   removeUI(paste0("#scale_row_",   rid), immediate = TRUE)
    for (rid in rv$writein_row_ids) removeUI(paste0("#writein_row_", rid), immediate = TRUE)
    rv$resp_row_ids    <- character(0)
    rv$scale_row_ids   <- character(0)
    rv$writein_row_ids <- character(0)
  }

  # ── Question type change ───────────────────────────────────────────────────
  observeEvent(input$questionType, {
    if (rv$suppress_type_change) return()
    clear_rows()
  }, ignoreInit = TRUE)

  # ── Add row buttons ────────────────────────────────────────────────────────
  observeEvent(input$add_response, {
    rid <- next_id()
    insertUI("#response_rows", "beforeEnd", make_response_row(rid), immediate = TRUE)
    rv$resp_row_ids <- c(rv$resp_row_ids, rid)
  })
  observeEvent(input$add_scale, {
    rid <- next_id()
    insertUI("#scale_rows", "beforeEnd", make_scale_row(rid), immediate = TRUE)
    rv$scale_row_ids <- c(rv$scale_row_ids, rid)
  })
  observeEvent(input$add_writein, {
    rid <- next_id()
    insertUI("#writein_rows", "beforeEnd", make_writein_row(rid), immediate = TRUE)
    rv$writein_row_ids <- c(rv$writein_row_ids, rid)
  })

  # ── Delete rows ────────────────────────────────────────────────────────────
  observeEvent(input$delete_resp_row, {
    rid <- input$delete_resp_row
    removeUI(paste0("#resp_row_", rid), immediate = TRUE)
    rv$resp_row_ids <- setdiff(rv$resp_row_ids, rid)
  })
  observeEvent(input$delete_scale_row, {
    rid <- input$delete_scale_row
    removeUI(paste0("#scale_row_", rid), immediate = TRUE)
    rv$scale_row_ids <- setdiff(rv$scale_row_ids, rid)
  })
  observeEvent(input$delete_writein_row, {
    rid <- input$delete_writein_row
    removeUI(paste0("#writein_row_", rid), immediate = TRUE)
    rv$writein_row_ids <- setdiff(rv$writein_row_ids, rid)
  })

  # ── Collect form state ─────────────────────────────────────────────────────
  collect_form <- reactive({
    qt          <- input$questionType %||% "selectOne"
    resp_labels <- sapply(rv$resp_row_ids, function(rid) input[[paste0("resp_label_", rid)]] %||% "")
    resp_rnames <- sapply(rv$resp_row_ids, function(rid) {
      v <- input[[paste0("resp_rname_", rid)]] %||% ""
      if (nchar(trimws(v)) == 0) to_rname(input[[paste0("resp_label_", rid)]] %||% "") else v
    })
    resp_values  <- sapply(rv$resp_row_ids,    function(rid) input[[paste0("resp_value_", rid)]] %||% "")
    scale_labels <- sapply(rv$scale_row_ids,   function(rid) input[[paste0("scale_label_", rid)]] %||% "")
    scale_values <- sapply(rv$scale_row_ids,   function(rid) input[[paste0("scale_value_", rid)]] %||% "")
    wi_labels    <- sapply(rv$writein_row_ids, function(rid) input[[paste0("wi_label_", rid)]] %||% "")
    wi_types     <- sapply(rv$writein_row_ids, function(rid) input[[paste0("wi_type_",  rid)]] %||% "character")
    wi_wnames    <- sapply(rv$writein_row_ids, function(rid) input[[paste0("wi_wname_", rid)]] %||% "")
    wname <- if (length(wi_wnames) > 0 && any(nchar(trimws(wi_wnames)) > 0))
      wi_wnames[nchar(trimws(wi_wnames)) > 0][1] else ""

    list(
      qname            = input$qname        %||% "",
      year             = input$year         %||% 2025,
      dname            = input$dname        %||% "",
      questionText     = input$questionText %||% "",
      questionType     = qt,
      text_pattern     = input$text_pattern %||% "",
      resp_labels      = resp_labels,
      rnames           = resp_rnames,
      resp_values      = resp_values,
      scale_row_labels = resp_labels,
      scale_opts       = scale_labels,
      scale_vals       = scale_values,
      wi_labels        = wi_labels,
      wi_types         = wi_types,
      wi_wnames        = wi_wnames,
      wname            = wname,
      notes_qname      = input$notes_qname %||% "",
      notes_year       = input$notes_year  %||% ""
    )
  })

  # ── Preview ────────────────────────────────────────────────────────────────
  output$preview <- renderText({
    d <- collect_form()
    if (nchar(trimws(d$qname)) == 0) return("# Fill in the form to see a preview...")
    tryCatch(build_man_call(d), error = function(e) paste("# Error:", e$message))
  })

  # ── Save ───────────────────────────────────────────────────────────────────
  observeEvent(input$save_record, {
    d <- collect_form()
    if (nchar(trimws(d$qname)) == 0) {
      showNotification("Please enter a name or question ID before saving.", type = "warning")
      return()
    }
    idx <- rv$editing_idx
    if (!is.null(idx)) {
      rv$records[[idx]] <- d
      rv$editing_idx <- NULL
      showNotification(paste0("Updated '", d$qname, "'."), type = "message")
    } else {
      rv$records <- c(rv$records, list(d))
      showNotification(paste0("Saved '", d$qname, "'."), type = "message")
    }
    do_clear_form()
  })

  # ── Clear form (year is intentionally NOT reset) ───────────────────────────
  do_clear_form <- function() {
    updateTextInput(session,      "qname",        value = "")
    # year intentionally kept
    updateTextInput(session,      "dname",         value = "")
    updateTextAreaInput(session,  "questionText",  value = "")
    updateSelectInput(session,    "questionType",  selected = "selectOne")
    updateTextInput(session,      "text_pattern",  value = "")
    updateTextAreaInput(session,  "notes_qname",   value = "")
    updateTextAreaInput(session,  "notes_year",    value = "")
    clear_rows()
    rv$editing_idx <- NULL
  }

  observeEvent(input$clear_form, do_clear_form())

  # ── Record list ────────────────────────────────────────────────────────────
  output$record_list <- renderUI({
    recs <- rv$records
    if (length(recs) == 0)
      return(div(style = "color:#6b7280; font-size:13px;", "No records saved yet."))
    tagList(lapply(seq_along(recs), function(i) {
      d <- recs[[i]]
      div(class = "record-card",
        fluidRow(
          column(8,
            tags$b(d$qname),
            tags$span(style = "color:#6b7280; font-size:12px; margin-left:8px;",
                      paste0(d$year, " · ", d$questionType))
          ),
          column(4, style = "text-align:right;",
            tags$button(class = "btn btn-xs btn-info", style = "margin-right:4px;",
              onclick = sprintf("Shiny.setInputValue('edit_record_idx',%d,{priority:'event'})", i),
              "Edit"),
            tags$button(class = "btn btn-xs btn-danger",
              onclick = sprintf("Shiny.setInputValue('delete_record_idx',%d,{priority:'event'})", i),
              "Delete")
          )
        )
      )
    }))
  })

  # ── Edit ───────────────────────────────────────────────────────────────────
  observeEvent(input$edit_record_idx, {
    i <- input$edit_record_idx
    d <- rv$records[[i]]
    rv$editing_idx       <- i
    rv$suppress_type_change <- TRUE
    clear_rows()
    updateTextInput(session,     "qname",        value = d$qname)
    updateNumericInput(session,  "year",          value = d$year)
    updateTextInput(session,     "dname",         value = d$dname %||% "")
    updateTextAreaInput(session, "questionText",  value = d$questionText)
    updateSelectInput(session,   "questionType",  selected = d$questionType)
    updateTextInput(session,     "text_pattern",  value = d$text_pattern %||% "")
    updateTextAreaInput(session, "notes_qname",   value = d$notes_qname %||% "")
    updateTextAreaInput(session, "notes_year",    value = d$notes_year  %||% "")
    qt <- d$questionType
    shinyjs::delay(200, {
      src_labels <- if (qt == "selectScale") d$scale_row_labels else d$resp_labels
      src_rnames <- d$rnames
      src_values <- if (qt == "selectScale") character(0) else d$resp_values
      for (j in seq_along(src_labels)) {
        rid     <- next_id()
        rname_j <- if (j <= length(src_rnames)) src_rnames[j] else ""
        value_j <- if (j <= length(src_values)) src_values[j] else ""
        insertUI("#response_rows", "beforeEnd",
                 make_response_row(rid, src_labels[j], rname_j, value_j), immediate = TRUE)
        rv$resp_row_ids <- c(rv$resp_row_ids, rid)
      }
      if (qt == "selectScale") {
        for (j in seq_along(d$scale_opts)) {
          rid   <- next_id()
          val_j <- if (j <= length(d$scale_vals)) d$scale_vals[j] else ""
          insertUI("#scale_rows", "beforeEnd",
                   make_scale_row(rid, d$scale_opts[j], val_j), immediate = TRUE)
          rv$scale_row_ids <- c(rv$scale_row_ids, rid)
        }
      }
      if (qt %in% c("selectOne", "selectMultiple")) {
        for (j in seq_along(d$wi_labels)) {
          rid     <- next_id()
          type_j  <- if (j <= length(d$wi_types))  d$wi_types[j]  else "character"
          wname_j <- if (!is.null(d$wi_wnames) && j <= length(d$wi_wnames)) d$wi_wnames[[j]] else ""
          insertUI("#writein_rows", "beforeEnd",
                   make_writein_row(rid, d$wi_labels[j], type_j, wname_j), immediate = TRUE)
          rv$writein_row_ids <- c(rv$writein_row_ids, rid)
        }
      }
      rv$suppress_type_change <- FALSE
    })
  })

  # ── Delete ─────────────────────────────────────────────────────────────────
  observeEvent(input$delete_record_idx, {
    i  <- input$delete_record_idx
    qn <- rv$records[[i]]$qname
    rv$records <- rv$records[-i]
    if (!is.null(rv$editing_idx) && rv$editing_idx == i) {
      rv$editing_idx <- NULL
      do_clear_form()
    }
    showNotification(paste0("Deleted '", qn, "'."), type = "warning")
  })

  # ── Download ───────────────────────────────────────────────────────────────
  output$download_r <- downloadHandler(
    filename = function() paste0("man_census_", Sys.Date(), ".R"),
    content  = function(file) {
      if (length(rv$records) == 0)
        writeLines("# No records saved.", file)
      else
        writeLines(generate_r_file(rv$records), file)
    }
  )
}

shinyApp(ui, server)
